"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "id" | "en" | "ar";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    // Menu items
    "menu.dashboard": "Dashboard",
    "menu.home": "Beranda",
    "menu.packages": "Paket & Aktivasi",
    "menu.progress": "Progress Modul",
    "menu.mainMenu": "Menu Utama",
    "menu.prayers": "Doa dan Dzikir",
    "menu.certificate": "Sertifikat",
    "menu.history": "Histori Aktivitas",
    "menu.reviews": "Ulasan",
    "menu.settings": "Pengaturan",
    "menu.profile": "Profil Saya",
    "menu.help": "Bantuan",
    "menu.logout": "Log Out",
    
    // Header
    "header.admin": "Administrator",
    "header.premium": "Jamaah Premium",
    
    // Dashboard Home
    "dashboard.welcome": "Selamat Datang,",
    "dashboard.subtitle": "Pantau kemajuan persiapan ibadah Anda dan akses simulasi manasik di sini.",
    "dashboard.quickStart": "Mulai Cepat",
    "dashboard.continueHaji": "Lanjutkan Manasik Haji",
    "dashboard.viewProgress": "Lihat Progress",
    "dashboard.overallProgress": "Progres Keseluruhan Perjalanan",
    "dashboard.modulesCompleted": "Modul Selesai",
    "dashboard.checklistCompleted": "Tugas Checklist Selesai",
    "dashboard.learningGuide": "Panduan Belajar",
    
    // Common / Buttons
    "button.close": "Tutup",
    "button.save": "Simpan",
    "button.submit": "Kirim",

    // Landing Page Navbar
    "nav.home": "Home",
    "nav.about": "Tentang Kami",
    "nav.features": "Fitur",
    "nav.pricing": "Harga",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.contact": "Hubungi Kami",
    "nav.register": "Daftar",
    "nav.login": "Masuk",

    // Landing Page Hero
    "landing.heroTag": "Pembelajaran Digital Imersif",
    "landing.heroTitle": "PERSIAPKAN IBADAH HAJI ANDA SECARA EFISIEN DAN IMERSIF",
    "landing.heroSubtitle": "Bahrain menghadirkan suasana Tanah Suci langsung ke hadapan Anda melalui teknologi VR 360° yang nyata dan mendalam.",
    "landing.btnStart": "Daftar Sekarang",
    "landing.btnFeatures": "Pelajari Fitur",
    
    // Landing Page Five Pillars
    "landing.pillarsSub": "Dasar-Dasar",
    "landing.pillarsTitle": "LIMA PILAR ISLAM",
    "landing.pillar1": "Syahadat",
    "landing.pillar2": "Shalat",
    "landing.pillar3": "Zakat",
    "landing.pillar4": "Puasa",
    "landing.pillar5": "Haji",
    
    // Landing Page Pricing
    "landing.priceTitle": "TEMUKAN PAKET TERBAIK UNTUK ANDA",
    "landing.priceSubtitle": "Pilih paket pembelajaran yang sesuai dengan kebutuhan Anda dan rasakan pengalaman manasik yang lebih nyata.",
    "landing.pkgBasic": "Paket Basic",
    "landing.pkgPremium": "Paket Premium",
    "landing.pkgTravel": "Paket Travel",
    "landing.pkgLansia": "Paket Lansia",
    "landing.priceFree": "Gratis",
    "landing.priceCustom": "Custom",
    "landing.btnChoose": "Pilih Paket",
    "landing.pkgBasicFeature1": "1 Modul VR",
    "landing.pkgBasicFeature2": "Audio Guide Basic",
    "landing.pkgBasicFeature3": "Akses 7 Hari",
    "landing.pkgPremiumFeature1": "Semua Modul 360°",
    "landing.pkgPremiumFeature2": "AI Ustadz Virtual",
    "landing.pkgPremiumFeature3": "Sertifikat Digital",
    "landing.pkgTravelFeature1": "Dashboard Monitoring",
    "landing.pkgTravelFeature2": "API Integration",
    "landing.pkgTravelFeature3": "Support Prioritas",
    "landing.pkgLansiaFeature1": "Navigasi Suara Penuh",
    "landing.pkgLansiaFeature2": "Kontrol Sederhana",
    "landing.pkgLansiaFeature3": "Bimbingan Personal",
    
    // Landing Page Why Bahrain
    "landing.whyTitle": "MENGAPA HARUS BAHRAIN?",
    "landing.why1Title": "Akurasi Visual 100%",
    "landing.why1Desc": "Semua lokasi difilmkan langsung di Tanah Suci menggunakan kamera resolusi 8K.",
    "landing.why2Title": "Pendampingan AI",
    "landing.why2Desc": "Bertanya tentang hukum manasik kapan saja dengan AI Ustadz yang terlatih.",
    "landing.why3Title": "Sertifikasi Resmi",
    "landing.why3Desc": "Dapatkan sertifikat digital setelah menyelesaikan seluruh rangkaian simulasi.",
    
    // Landing Page Testimonials
    "landing.testiSub": "Apa Kata Mereka?",
    "landing.testiTitle": "TESTIMONI TERBARU JAMAAH KAMI",
    "landing.testiDesc": "Dengarkan cerita jujur dari para jamaah yang telah mematangkan persiapan ibadah haji mereka bersama Bahrain.",
    "landing.noTestimonials": "Belum ada testimoni terbaru yang disubmit.",

    // Landing Page Blog
    "landing.blogSub": "Artikel & Berita Terbaru",
    "landing.blogTitle": "PANDUAN & FIKIH MANASIK TERBAIK",
    "landing.blogDesc": "Perkaya ilmu manasik Anda melalui kumpulan artikel panduan, fikih praktis, dan tips perjalanan haji yang dikuratori ustadz ahli.",
    "landing.noBlogs": "Belum ada artikel panduan yang diterbitkan.",
    "landing.blogReadMore": "Baca Selengkapnya",

    // Footer
    "footer.desc": "Membantu jamaah Indonesia mempersiapkan perjalanan spiritual terbaik mereka melalui teknologi imersif yang nyata dan terpercaya.",
    "footer.nav": "Navigasi",
    "footer.support": "Dukungan",
    "footer.contact": "Hubungi Kami",
    "footer.contactDesc": "Punya pertanyaan? Kami siap membantu persiapan Anda.",
    "footer.copyright": "© 2026 Bahrain. Seluruh hak cipta dilindungi oleh Allah SWT.",
    "footer.mainFeatures": "Fitur Utama",
    "footer.pricePlans": "Paket Harga",
    "footer.helpCenter": "Pusat Bantuan",
    "footer.privacy": "Kebijakan Privasi",
    "footer.terms": "Syarat & Ketentuan",

    // About Page
    "about.tag": "Tentang Kami",
    "about.heroTitle": "Menghubungkan Hati dengan Tanah Suci Melalui Teknologi",
    "about.heroSubtitle": "Bahrain lahir dari keinginan untuk membantu setiap jamaah merasakan ketenangan dan kesiapan maksimal sebelum melangkah ke Baitullah.",
    "about.statsDesc": "Jamaah telah terbantu mempersiapkan haji & umrah.",
    "about.missionTitle": "Misi Perjalanan Kami",
    "about.missionDesc1": "Kami memahami bahwa perjalanan Haji dan Umrah adalah momen sekali seumur hidup yang paling sakral. Namun, ketidaktahuan akan situasi lapangan seringkali menimbulkan kecemasan bagi calon jamaah, terutama lansia.",
    "about.missionDesc2": "Bahrain hadir sebagai jembatan imersif. Dengan teknologi VR 360°, kami menghadirkan simulasi nyata yang memungkinkan jamaah \"berada\" di lokasi sebenarnya, menghafal rute, dan memahami rukun secara visual sebelum keberangkatan.",
    "about.visionTitle": "Visi Kami",
    "about.visionDesc": "Menjadi platform edukasi manasik digital nomor satu di dunia yang menggabungkan syariat dan teknologi.",
    "about.valuesTitle": "Nilai Kami",
    "about.valuesDesc": "Amanah dalam menyampaikan ilmu, Inovatif dalam teknologi, dan Imersif dalam pengalaman.",
    "about.whyTitle": "Kenapa Bahrain Berbeda?",
    "about.whySubtitle": "Inovasi kami dirancang untuk memudahkan, bukan mempersulit.",
    "about.why1Title": "Akurasi 8K",
    "about.why1Desc": "Semua visual diambil langsung di lokasi nyata dengan resolusi ultra-tinggi untuk detail maksimal.",
    "about.why2Title": "Kurikulum Terintegrasi",
    "about.why2Desc": "Materi disusun bersama ustadz pembimbing berpengalaman sesuai syariat yang sahih.",
    "about.why3Title": "Aksesibilitas Tinggi",
    "about.why3Desc": "Dapat diakses melalui smartphone, tablet, komputer, hingga headset VR profesional.",
    "about.ctaTitle": "Mari Bergabung dalam Revolusi Manasik Digital",
    "about.ctaSubtitle": "Tingkatkan kesiapan ibadah Anda atau jamaah travel Anda sekarang juga.",
    "about.ctaStart": "Mulai Sekarang",

    // Pricing Page
    "price.heroTitle": "Investasikan Persiapan Ibadah Anda",
    "price.heroSubtitle": "Pilih paket yang paling sesuai dengan kebutuhan Anda untuk pengalaman manasik yang lebih matang.",
    "price.popular": "Paling Populer",
    "price.descBasic": "Cocok untuk pengenalan awal manasik.",
    "price.descPremium": "Pengalaman penuh untuk jamaah individu.",
    "price.descTravel": "Solusi efisien untuk biro perjalanan.",
    "price.descLansia": "Bimbingan ekstra untuk orang tua tercinta.",
    "price.btnFree": "Mulai Gratis",
    "price.btnPremium": "Beli Paket Premium",
    "price.btnSales": "Hubungi Penjualan",
    "price.btnLansia": "Beli Paket Khusus",
    "price.helpTitle": "Butuh Bantuan Memilih?",
    "price.helpDesc": "Tim kami siap membantu Anda memilih paket terbaik atau memberikan demo khusus untuk biro perjalanan Haji & Umrah Anda.",
    "price.btnWa": "Hubungi Kami via WhatsApp",
    "price.featBasic1": "1 Modul VR Utama (Ihram)",
    "price.featBasic2": "Panduan Audio Dasar",
    "price.featBasic3": "Teks Doa Lengkap",
    "price.featBasic4": "Akses 7 Hari",
    "price.featPrem1": "Semua Modul 360°",
    "price.featPrem2": "AI Ustadz Virtual 24/7",
    "price.featPrem3": "Sertifikat Digital",
    "price.featPrem4": "Akses Selamanya",
    "price.featPrem5": "Update Konten Berkala",
    "price.featTrav1": "Dashboard Monitoring Jamaah",
    "price.featTrav2": "Branding Nama Travel",
    "price.featTrav3": "Akses untuk 50+ Jamaah",
    "price.featTrav4": "API Integration",
    "price.featTrav5": "Support Prioritas",
    "price.featLan1": "Navigasi Voice-Command",
    "price.featLan2": "Interface Sangat Sederhana",
    "price.featLan3": "Bimbingan Video Call (1x)",
    "price.featLan4": "Semua Fitur Premium",
    "price.featLan5": "Pendampingan Login",

    // FAQ Page
    "faq.sub": "Frequently Asked Questions",
    "faq.title": "PERTANYAAN UMUM",
    "faq.desc": "Semua yang perlu Anda ketahui tentang pengalaman baru belajar manasik.",
    "faq.cat1": "Seputar Bahrain",
    "faq.q1": "Apa itu Bahrain?",
    "faq.a1": "Bahrain adalah platform edukasi ibadah Haji dan Umroh berbasis teknologi Virtual Reality (VR) 360 derajat yang memungkinkan jamaah merasakan pengalaman simulasi nyata di Tanah Suci.",
    "faq.q2": "Apakah aplikasi ini gratis?",
    "faq.a2": "Kami menyediakan Paket Basic secara gratis untuk mencoba beberapa modul. Untuk akses penuh ke seluruh lokasi dan fitur premium, tersedia paket berlangganan yang terjangkau.",
    "faq.q3": "Perangkat apa saja yang didukung?",
    "faq.a3": "Bahrain dapat diakses melalui Smartphone (Android/iOS), Tablet, Laptop, maupun PC. Untuk pengalaman maksimal, kami menyarankan penggunaan kacamata VR.",
    "faq.cat2": "Teknologi & VR",
    "faq.q4": "Haruskah saya punya kacamata VR?",
    "faq.a4": "Tidak wajib. Anda tetap bisa menikmati konten 360 derajat dengan menggerakkan layar HP atau kursor mouse. Namun, kacamata VR akan memberikan sensasi imersif yang jauh lebih nyata.",
    "faq.q5": "Apakah kacamata VR yang digunakan khusus?",
    "faq.a5": "Platform kami kompatibel dengan hampir semua VR Box standar maupun perangkat VR high-end seperti Oculus/Meta Quest.",
    "faq.cat3": "Akun & Pembayaran",
    "faq.q6": "Bagaimana cara aktivasi paket?",
    "faq.a6": "Setelah melakukan pembayaran, Anda akan menerima kode aktivasi atau paket Anda akan otomatis aktif jika menggunakan metode pembayaran instan (QRIS/Transfer Bank).",
    "faq.q7": "Apakah bisa digunakan untuk rombongan travel?",
    "faq.a7": "Sangat bisa. Kami memiliki paket khusus Biro Travel yang dilengkapi dashboard monitoring untuk melihat progres setiap jamaah.",
    "faq.ctaTitle": "Masih punya pertanyaan lain?",
    "faq.ctaDesc": "Tim dukungan kami siap menjawab segala keraguan Anda mengenai penggunaan platform Bahrain.",
    "faq.ctaBtn": "Hubungi Tim CS",

    // Contact Page
    "contact.sub": "Get in Touch",
    "contact.title": "HUBUNGI KAMI",
    "contact.desc": "Kami di sini untuk membantu Anda mempersiapkan perjalanan spiritual terbaik dalam hidup Anda.",
    "contact.formTitle": "Kirim Pesan",
    "contact.formDesc": "Ada pertanyaan khusus? Isi form di bawah dan tim kami akan membalas Anda dalam 24 jam.",
    "contact.labelName": "Nama Lengkap",
    "contact.phName": "Nama Anda",
    "contact.labelEmail": "Email",
    "contact.labelSubject": "Subjek",
    "contact.optSubject1": "Pertanyaan Umum",
    "contact.optSubject2": "Aktivasi Paket",
    "contact.optSubject3": "Kerjasama Biro Travel",
    "contact.optSubject4": "Kendala Teknis VR",
    "contact.labelMessage": "Pesan",
    "contact.phMessage": "Tuliskan pesan Anda di sini...",
    "contact.btnSubmit": "Kirim Sekarang",
    "contact.infoOffice": "Kantor Pusat",
    "contact.infoOfficeDesc": "Jl. Jendral Sudirman No. 12, Senayan, Jakarta Selatan, 12190",
    "contact.infoPhone": "Hubungi Kami",
    "contact.infoEmail": "Dukungan Email",

    // Auth Pages
    "auth.welcomeBack": "Selamat Datang Kembali",
    "auth.loginSubtitle": "Masuk untuk melanjutkan pengalaman manasik Anda",
    "auth.emailLabel": "Alamat Email",
    "auth.passwordLabel": "Kata Sandi",
    "auth.forgotPassword": "Lupa kata sandi?",
    "auth.rememberMe": "Ingat saya",
    "auth.btnLogin": "Masuk Sekarang",
    "auth.orWith": "Atau masuk dengan",
    "auth.noAccount": "Belum punya akun?",
    "auth.registerFree": "Daftar Gratis",
    "auth.createAccount": "Buat Akun Baru",
    "auth.registerSubtitle": "Mulai perjalanan manasik digital Anda hari ini",
    "auth.nameLabel": "Nama Lengkap",
    "auth.phName": "Masukkan nama lengkap Anda",
    "auth.phPassword": "Minimal 8 karakter",
    "auth.termsAgree": "Saya setuju dengan",
    "auth.termsLink": "Syarat & Ketentuan",
    "auth.and": "serta",
    "auth.privacyLink": "Kebijakan Privasi",
    "auth.btnRegister": "Daftar Sekarang",
    "auth.orRegisterWith": "Atau daftar dengan",
    "auth.haveAccount": "Sudah punya akun?",
    "auth.loginLink": "Masuk Sekarang",

    // Dashboard Home Content
    "dashboard.progTitle": "Progress Modul",
    "dashboard.progDesc": "Pantau perkembangan kesiapan ibadah Haji & Umrah Anda secara real-time.",
    "dashboard.heroTitle": "Apa itu VR Haji 360°?",
    "dashboard.heroDesc": "VR Haji menghadirkan simulasi interaktif untuk merasakan pengalaman ibadah Haji secara nyata.",
    "dashboard.watchNow": "Tonton Sekarang",

    // Dashboard Packages Content
    "dashpkg.title": "Paket & Aktivasi",
    "dashpkg.subtitle": "Kelola paket langganan Anda atau aktivasi modul baru di sini.",
    "dashpkg.featuredFeatures": "FITUR UNGGULAN:",
    "dashpkg.btnBuy": "Beli Sekarang",
    "dashpkg.currentPkg": "Paket Anda Saat Ini",
    "dashpkg.voucherTitle": "Aktivasi Kode Voucher",
    "dashpkg.voucherDesc": "Punya kode aktivasi dari Travel Haji atau hadiah? Masukkan kodenya di bawah ini untuk membuka akses materi secara instan.",
    "dashpkg.voucherPlaceholder": "Masukkan kode voucher...",
    "dashpkg.voucherBtn": "Aktivasi Sekarang",
    "dashpkg.active": "Aktif",
    "dashpkg.popular": "Terpopuler",
    "dashpkg.basicName": "Paket Dasar",
    "dashpkg.basicPeriod": "/ sekali bayar",
    "dashpkg.basicFeat1": "Akses semua video materi",
    "dashpkg.basicFeat2": "Modul Ihram & Tawaf (360°)",
    "dashpkg.basicFeat3": "E-Sertifikat Dasar",
    "dashpkg.basicFeat4": "Akses selamanya",
    "dashpkg.premName": "Paket Premium VR",
    "dashpkg.premPeriod": "/ sekali bayar",
    "dashpkg.premFeat1": "Semua fitur Paket Dasar",
    "dashpkg.premFeat2": "Akses Full VR Experience (360°)",
    "dashpkg.premFeat3": "Konsultasi AI Ustadz 24/7",
    "dashpkg.premFeat4": "Materi Manasik Lansia",
    "dashpkg.premFeat5": "Prioritas Update Modul",
    "dashpkg.travName": "Paket Travel Haji",
    "dashpkg.travPeriod": "/ 50 Lisensi",
    "dashpkg.travFeat1": "Dashboard Monitoring Jamaah",
    "dashpkg.travFeat2": "Custom Branding Travel",
    "dashpkg.travFeat3": "Laporan Progress Jamaah",
    "dashpkg.travFeat4": "Integrasi Jadwal Travel",
    "dashpkg.travFeat5": "Support Teknis 24/7",
    // Progress Module
    "progress.title": "Progress Modul",
    "progress.totalCompletedLabel": "Total Selesai",
    "progress.completedStatusText": "Anda telah menyelesaikan {count} dari 6 modul utama. Terus tingkatkan!",
    "progress.subtitle": "Ikuti urutan bimbingan manasik di bawah secara berurutan sesuai ketentuan Rukun & Wajib Haji.",
    "progress.tipTitle": "Terus Berikan yang Terbaik!",
    "progress.tipDesc": "Tuntaskan setiap langkah rukun haji secara disiplin untuk meraih kesempurnaan ibadah.",
    "progress.certTitle": "Unduh Sertifikat Progress",
    "progress.certDesc": "Dapatkan sertifikat sementara untuk setiap modul yang Anda selesaikan.",
    "progress.lockedToast": "Modul Terkunci!\nSilakan selesaikan modul sebelumnya terlebih dahulu sampai 100% untuk membuka perjalanan manasik berikutnya.",
    "progress.videoWarning": "Peringatan:\nAnda belum selesai menonton minimal 10 detik. Progres bimbingan video Anda tidak akan disimpan.",
    "progress.learningPortal": "Pintu Pembelajaran Manasik",
    "progress.videoStep": "Langkah 1: Video Tutorial",
    "progress.videoStepDesc": "Tonton bimbingan visual cara pelaksanaan (20% progres)",
    "progress.doaStep": "Langkah 2: Doa & Dzikir khusus",
    "progress.doaStepDesc": "Dengarkan do\'a wajib yang dibaca (20% progres)",
    "progress.vrStep": "Langkah 3: Simulasi VR 360°",
    "progress.vrStepDesc": "Tuntaskan semua tugas interaktif lapangan (60% progres)",
    "progress.totalProgress": "Total Progres Modul",
    "progress.totalProgressDesc": "Selesaikan 3 langkah di atas untuk 100% kelulusan modul ini.",
    "progress.btnWatch": "Tonton Video",
    "progress.btnOpenDoa": "Buka Doa",
    "progress.btnStartVR": "Mulai VR",
    "progress.btnComplete": "Saya Telah Menghafal & Selesai",
    "progress.btnBack": "Kembali ke Portal Langkah",
    "progress.btnListen": "Dengarkan",
    "progress.btnPause": "Jeda Audio",
    "progress.btnDone": "Selesai",
    "progress.locked": "Terkunci",
    "progress.videoCompleted": "Selesai Menonton Video: {name}",
    "progress.doaCompleted": "Menghafal Doa: {name}",
    "progress.videoHeader": "Video Tutorial Modul",
    "progress.videoIntro": "Pengantar",
    "progress.videoReq": "Persyaratan Kelulusan:",
    "progress.videoFinished": "✅ Video Selesai Ditonton",
    "progress.videoWatching": "⏱️ Menonton: {watched}s / 10s",
    "progress.doaHeader": "Doa & Dzikir Rukun",
    "progress.doaIntro": "Doa Khusus",
    "progress.recapTitle": "Rekap Pembelajaran",
    "progress.downloadReport": "Download Report",
    "progress.thMod": "Modul",
    "progress.thStatus": "Status",
    "progress.thProgress": "Progres",
    "progress.thTime": "Waktu",
    "progress.lastAccess": "Terakhir akses:",
    "progress.videoCompletedLabel": "Video",
    "progress.doaCompletedLabel": "Doa",
    "progress.tasksLabel": "Tugas",

    "module.ihram.name": "Modul 1: Ihram & Miqat",
    "module.ihram.desc": "Persiapan mengenakan kain ihram, larangan ihram, dan melafalkan niat Haji/Umrah di titik Miqat.",
    "module.tawaf.name": "Modul 2: Tawaf di Ka\'bah",
    "module.tawaf.desc": "Mengelilingi Ka\'bah sebanyak 7 putaran diawali dari garis Hajar Aswad disertai doa khusus.",
    "module.sai.name": "Modul 3: Sa\'i Safa-Marwah",
    "module.sai.desc": "Berjalan dan lari-lari kecil sebanyak 7 kali perjalanan antara Bukit Safa dan Bukit Marwah.",
    "module.wukuf.name": "Modul 4: Wukuf di Arafah",
    "module.wukuf.desc": "Berdiam diri, merenung, berzikir khusyuk, dan shalat di Padang Arafah pada 9 Dzulhijjah.",
    "module.muzdalifah.name": "Modul 5: Mabit di Muzdalifah",
    "module.muzdalifah.desc": "Bermalam sejenak di Muzdalifah setelah sunset dari Arafah untuk berzikir dan mencari kerikil.",
    "module.jumrah.name": "Modul 6: Melontar Jumrah",
    "module.jumrah.desc": "Melontar Jumrah Ula, Wustha, dan Aqabah di Jamarat menggunakan kerikil sebagai simbol perlawanan setan.",

    // Prayers Page
    "prayers.title": "Doa & Dzikir",
    "prayers.subtitle": "Kumpulan doa-doa mustajab selama perjalanan ibadah Haji & Umrah Anda.",
    "prayers.searchPlaceholder": "Cari doa tertentu...",
    "prayers.noResults": "Tidak menemukan doa yang cocok dengan pencarian Anda.",
    "prayers.btnPlay": "Putar Audio",
    "prayers.btnPause": "Jeda Audio",
    "prayers.tipTitle": "Tips Menghafal Doa",
    "prayers.tipDesc": "Gunakan tombol Putar Audio di atas untuk mendengarkan lafalan doa yang fasih secara berulang-ulang. Menghafal dengan mendengarkan langsung pelafalan syekh/ustad terbukti mempercepat hafalan hingga 3x lipat!",
    "prayers.meaning": "Artinya:",
    
    // Categories
    "prayers.cat.all": "Semua",
    "prayers.cat.ihram": "Persiapan Ihram",
    "prayers.cat.tawaf": "Thawaf",
    "prayers.cat.sai": "Sa\'i",
    "prayers.cat.wukuf": "Wukuf",
    "prayers.cat.jumrah": "Lontar Jumrah",

    // Specific Prayers
    "prayer.ihram.title": "Lafal Niat Ihram Haji & Umrah",
    "prayer.ihram.trans": "Aku berniat melaksanakan ibadah haji dan berihram karena Allah Ta\'ala.",
    "prayer.talbiyah.title": "Kalimat Talbiyah Utama",
    "prayer.talbiyah.trans": "Aku memenuhi panggilan-Mu ya Allah, aku memenuhi panggilan-Mu. Aku memenuhi panggilan-Mu, tidak ada sekutu bagi-Mu, aku memenuhi panggilan-Mu. Sesungguhnya segala puji, nikmat dan kerajaan adalah milik-Mu, tidak ada sekutu bagi-Mu.",
    "prayer.tawaf.title": "Doa Memulai Hajar Aswad (Tawaf)",
    "prayer.tawaf.trans": "Dengan menyebut nama Allah, Allah Maha Besar. Ya Allah, aku beriman kepada-Mu, membenarkan kitab-Mu, dan memenuhi janji-Mu.",
    "prayer.sapujagad.title": "Doa Sapu Jagad (Rukun Yamani)",
    "prayer.sapujagad.trans": "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.",
    "prayer.sai.title": "Doa Naik Bukit Safa (Mulai Sa\'i)",
    "prayer.sai.trans": "Sesungguhnya Safa dan Marwah adalah sebagian dari syiar Allah. Aku memulai dengan apa yang Allah memulai dengannya.",
    "prayer.wukuf.title": "Doa Utama Wukuf di Arafah",
    "prayer.wukuf.trans": "Tidak ada Tuhan selain Allah Yang Maha Esa, tidak ada sekutu bagi-Nya. Bagi-Nya segala kerajaan dan bagi-Nya segala puji. Dia Maha Kuasa atas segala sesuatu.",
    "prayer.jumrah.title": "Doa Saat Melontar Jumrah",
    "prayer.jumrah.trans": "Dengan menyebut nama Allah, Allah Maha Besar. Lemparan ini sebagai penolak setan dan keridaan bagi Allah Yang Maha Pengasih.",
    "prayer.muzdalifah.title": "Zikir Mabit Muzdalifah",
    "prayer.muzdalifah.trans": "Maka berzikirlah kepada Allah di tempat yang mulia (Masy\'aril Haram).",

    // Certificate Page
    "cert.title": "Sertifikat & Pencapaian",
    "cert.subtitle": "Bukti nyata kesungguhan Anda dalam mempersiapkan perjalanan suci.",
    "cert.btnDownload": "Download PDF",
    "cert.btnShare": "Bagikan ke Media Sosial",
    "cert.sidebarTitle": "Badge Pencapaian",
    "cert.whyTitle": "Mengapa Sertifikat Ini Penting?",
    "cert.whyDesc": "Sertifikat ini menunjukkan bahwa Anda telah menguasai rukun, wajib, dan tata cara manasik secara visual dan teoritis, meningkatkan kepercayaan diri Anda di lapangan nanti.",
    "cert.pending": "Pending Completion",
    "cert.inProgress": "Berlangsung",
    "cert.unlockedDesc": "Selesai",
    "cert.achIhram": "Pioneer Ihram",
    "cert.achTawaf": "Thawaf Master",
    "cert.achPilgrim": "Patient Pilgrim",

    // History Page
    "history.title": "Histori Aktivitas",
    "history.subtitle": "Rekaman jejak persiapan ibadah Anda dari waktu ke waktu.",
    "history.btnFilter": "Filter Tipe",
    "history.btnSort": "Urutkan Terbaru",
    "history.statSesi": "Total Sesi Belajar",
    "history.statWaktu": "Waktu Simulasi",
    "history.statDoa": "Doa yang Dihafal",
    "history.empty": "Belum ada histori aktivitas. Mulailah belajar di halaman modul!",
    "history.btnLoadMore": "Muat Aktivitas Sebelumnya",
    "history.unitSesi": "Sesi",
    "history.unitJam": "Jam",
    "history.unitMenit": "Menit",
    "history.unitDoa": "Doa",
    "history.typeBelajar": "Belajar",
    "history.typeSimulasi": "Simulasi",
    "history.typeHafalan": "Hafalan",

    // Reviews Page
    "reviews.title": "Ulasan Pengguna",
    "reviews.subtitle": "Dengarkan pengalaman jamaah lain atau bagikan cerita Anda sendiri.",
    "reviews.avgRating": "Rating Rata-rata",
    "reviews.basedOn": "Berdasarkan {count} ulasan",
    "reviews.shareTitle": "Bagikan Pengalaman Anda",
    "reviews.shareDesc": "Bantu jamaah lain dengan memberikan ulasan mengenai pengalaman Anda menggunakan simulasi Bahrain.",
    "reviews.btnWrite": "Tulis Ulasan Sekarang",
    "reviews.empty": "Belum ada ulasan yang dibuat. Jadilah yang pertama memberikan ulasan!",
    "reviews.btnLoadMore": "Lihat Lebih Banyak Ulasan",
    
    // Review Modal
    "reviews.modalTitle": "Tulis Ulasan Anda",
    "reviews.modalRating": "Rating Anda",
    "reviews.modalComment": "Komentar / Pengalaman",
    "reviews.modalPlaceholder": "Ceritakan pengalaman Anda selama menggunakan platform manasik Bahrain...",
    "reviews.modalBtnCancel": "Batal",
    "reviews.modalBtnSubmit": "Kirim Ulasan",
    "reviews.success": "Ulasan berhasil dikirim!",
    "reviews.error": "Gagal mengirim ulasan.",

    // Profile Page
    "profile.title": "Pengaturan Profil",
    "profile.subtitle": "Kelola informasi pribadi dan preferensi akun Anda secara real-time.",
    "profile.memberId": "ID Anggota",
    "profile.securityTip": "Data Anda aman dan terenkripsi. Kami tidak akan membagikan informasi pribadi Anda kepada pihak manapun.",
    "profile.labelName": "Nama Lengkap",
    "profile.labelEmail": "Email",
    "profile.labelPhone": "No. WhatsApp",
    "profile.labelLocation": "Lokasi / Kota",
    "profile.labelSecurity": "Keamanan Akun",
    "profile.labelNewPassword": "Password Baru",
    "profile.labelConfirmPassword": "Konfirmasi Password",
    "profile.phNewPassword": "Ketik password baru...",
    "profile.phConfirmPassword": "Ulangi password baru...",
    "profile.btnSave": "Simpan Perubahan",
    "profile.success": "Profil berhasil diperbarui!",
    "profile.errName": "Nama tidak boleh kosong",
    "profile.errEmail": "Email tidak boleh kosong",
    "profile.errConfirm": "Konfirmasi password tidak cocok",
    "profile.errLength": "Password baru minimal harus 6 karakter",
    "profile.errSave": "Gagal memperbarui profil.",
    "profile.errConn": "Terjadi kesalahan koneksi server.",

    // Help Page
    "help.title": "Pusat Bantuan",
    "help.subtitle": "Temukan jawaban tercepat untuk pertanyaan dan kendala Anda.",
    "help.catVR": "Tutorial VR",
    "help.catVRDesc": "Cara menggunakan kacamata VR dan navigasi simulasi.",
    "help.catAccount": "Akun & Billing",
    "help.catAccountDesc": "Masalah login, aktivasi paket, dan pembayaran.",
    "help.catMaterials": "Materi Manasik",
    "help.catMaterialsDesc": "Penjelasan mengenai urutan dan konten edukasi.",
    "help.faqTitle": "Pertanyaan Umum (FAQ)",
    
    // Contact Support
    "help.supportTitle": "Butuh Bantuan Lebih?",
    "help.supportSubTitle": "Hubungi Tim Kami",
    "help.supportDesc": "Tim support kami siap membantu Anda setiap hari (08:00 - 21:00 WIB).",
    "help.whatsapp": "WhatsApp Support",
    "help.email": "Email Support",
    
    // Feedback
    "help.feedbackTitle": "Punya Feedback?",
    "help.feedbackDesc": "Kami selalu terbuka untuk saran agar Bahrain menjadi lebih baik bagi seluruh jamaah.",
    "help.feedbackLink": "Kirim Feedback",
    
    // Feedback Modal
    "help.modalTitle": "Kirim Feedback",
    "help.modalDesc": "Saran dan kritik Anda sangat berharga untuk pengembangan platform Bahrain.",
    "help.modalTopic": "Topik Feedback",
    "help.modalOpt1": "Kendala Simulasi VR",
    "help.modalOpt2": "Usulan Fitur Baru",
    "help.modalOpt3": "Masukan Kurikulum",
    "help.modalOpt4": "Lainnya",
    "help.modalMessage": "Pesan Masukan",
    "help.modalPlaceholder": "Tuliskan saran atau kendala detail Anda di sini...",
    "help.modalBtnCancel": "Batal",
    "help.modalBtnSubmit": "Kirim Feedback",
    "help.feedbackSuccess": "Feedback berhasil dikirim! Terima kasih atas masukan Anda.",
    "help.feedbackError": "Gagal mengirim feedback.",
    
    // FAQs Detail
    "help.faq.q1": "Bagaimana cara mengaktifkan paket Premium VR?",
    "help.faq.a1": "Anda dapat memasukkan kode voucher yang didapat dari biro travel di halaman \'Paket & Aktivasi\', atau melakukan pembelian langsung melalui WhatsApp admin kami.",
    "help.faq.q2": "Apakah aplikasi ini bisa digunakan tanpa kacamata VR?",
    "help.faq.a2": "Bisa. Anda tetap dapat menikmati simulasi dalam mode 360 derajat biasa melalui layar smartphone atau komputer Anda.",
    "help.faq.q3": "Sertifikat saya tidak bisa diunduh, apa solusinya?",
    "help.faq.a3": "Pastikan semua modul di halaman \'Progress Modul\' sudah berstatus 100%. Jika sudah namun tetap bermasalah, silakan hubungi tim IT kami.",
    "help.faq.q4": "Apakah data progres saya akan tersimpan jika ganti perangkat?",
    "help.faq.a4": "Ya, semua progres Anda tersimpan secara cloud di akun Anda. Cukup login kembali dengan email yang sama di perangkat baru.",
    "cert.locked": "Sertifikat Terkunci",
    "cert.lockedDesc": "Selesaikan seluruh kurikulum Bahrain untuk mengunduh sertifikat resmi Anda.",
    "cert.issuedDateLabel": "Tanggal Terbit",
    "cert.idLabel": "ID Sertifikat",
    "cert.completionDesc": "Telah berhasil menyelesaikan seluruh rangkaian program simulasi manasik haji digital dan dinyatakan siap secara teori untuk melaksanakan ibadah di Tanah Suci.",
  },
  en: {
    // Menu items
    "menu.dashboard": "Dashboard",
    "menu.home": "Home",
    "menu.packages": "Packages & Activation",
    "menu.progress": "Module Progress",
    "menu.mainMenu": "Main Menu",
    "menu.prayers": "Prayers & Dzikir",
    "menu.certificate": "Certificate",
    "menu.history": "Activity History",
    "menu.reviews": "Reviews",
    "menu.settings": "Settings",
    "menu.profile": "My Profile",
    "menu.help": "Help & Support",
    "menu.logout": "Log Out",
    
    // Header
    "header.admin": "Administrator",
    "header.premium": "Premium User",
    
    // Dashboard Home
    "dashboard.welcome": "Welcome,",
    "dashboard.subtitle": "Monitor your worship preparation progress and access your manasik simulation here.",
    "dashboard.quickStart": "Quick Start",
    "dashboard.continueHaji": "Continue Haji Manasik",
    "dashboard.viewProgress": "View Progress",
    "dashboard.overallProgress": "Overall Journey Progress",
    "dashboard.modulesCompleted": "Modules Completed",
    "dashboard.checklistCompleted": "Checklist Tasks Completed",
    "dashboard.learningGuide": "Learning Guide",
    
    // Common / Buttons
    "button.close": "Close",
    "button.save": "Save",
    "button.submit": "Submit",

    // Landing Page Navbar
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.contact": "Contact Us",
    "nav.register": "Register",
    "nav.login": "Login",

    // Landing Page Hero
    "landing.heroTag": "Immersive Digital Learning",
    "landing.heroTitle": "PREPARE YOUR HAJI WORSHIP EFFICIENTLY AND IMMERSIVELY",
    "landing.heroSubtitle": "Bahrain brings the atmosphere of the Holy Land directly to you through realistic and deep 360° VR technology.",
    "landing.btnStart": "Register Now",
    "landing.btnFeatures": "Learn Features",
    
    // Landing Page Five Pillars
    "landing.pillarsSub": "Fundamentals",
    "landing.pillarsTitle": "FIVE PILLARS OF ISLAM",
    "landing.pillar1": "Shahada",
    "landing.pillar2": "Salah",
    "landing.pillar3": "Zakat",
    "landing.pillar4": "Sawm (Fasting)",
    "landing.pillar5": "Hajj",
    
    // Landing Page Pricing
    "landing.priceTitle": "FIND THE BEST PACKAGE FOR YOU",
    "landing.priceSubtitle": "Choose a learning package that suits your needs and feel a more realistic manasik experience.",
    "landing.pkgBasic": "Basic Package",
    "landing.pkgPremium": "Premium Package",
    "landing.pkgTravel": "Travel Package",
    "landing.pkgLansia": "Elderly Package",
    "landing.priceFree": "Free",
    "landing.priceCustom": "Custom",
    "landing.btnChoose": "Choose Package",
    "landing.pkgBasicFeature1": "1 VR Module",
    "landing.pkgBasicFeature2": "Basic Audio Guide",
    "landing.pkgBasicFeature3": "7 Days Access",
    "landing.pkgPremiumFeature1": "All 360° Modules",
    "landing.pkgPremiumFeature2": "Virtual AI Ustadz",
    "landing.pkgPremiumFeature3": "Digital Certificate",
    "landing.pkgTravelFeature1": "Monitoring Dashboard",
    "landing.pkgTravelFeature2": "API Integration",
    "landing.pkgTravelFeature3": "Priority Support",
    "landing.pkgLansiaFeature1": "Full Voice Navigation",
    "landing.pkgLansiaFeature2": "Simple Controls",
    "landing.pkgLansiaFeature3": "Personal Guidance",
    
    // Landing Page Why Bahrain
    "landing.whyTitle": "WHY SHOULD YOU CHOOSE BAHRAIN?",
    "landing.why1Title": "100% Visual Accuracy",
    "landing.why1Desc": "All locations are filmed directly in the Holy Land using 8K resolution cameras.",
    "landing.why2Title": "AI Assistance",
    "landing.why2Desc": "Ask about manasik laws anytime with a trained AI Ustadz.",
    "landing.why3Title": "Official Certification",
    "landing.why3Desc": "Get a digital certificate after completing the entire simulation series.",
    
    // Landing Page Testimonials
    "landing.testiSub": "What Do They Say?",
    "landing.testiTitle": "OUR PILGRIMS' LATEST TESTIMONIALS",
    "landing.testiDesc": "Hear honest stories from pilgrims who have finalized their Haji preparation with Bahrain.",
    "landing.noTestimonials": "No recent testimonials submitted yet.",

    // Landing Page Blog
    "landing.blogSub": "Latest Articles & News",
    "landing.blogTitle": "BEST GUIDE & FIQH OF MANASIK",
    "landing.blogDesc": "Enrich your manasik knowledge through a collection of guide articles, practical fiqh, and travel tips curated by expert ustadz.",
    "landing.noBlogs": "No guide articles published yet.",
    "landing.blogReadMore": "Read More",

    // Footer
    "footer.desc": "Helping pilgrims prepare their best spiritual journey through realistic and trusted immersive technology.",
    "footer.nav": "Navigation",
    "footer.support": "Support",
    "footer.contact": "Contact Us",
    "footer.contactDesc": "Have questions? We are ready to help with your preparation.",
    "footer.copyright": "© 2026 Bahrain. All rights reserved by Allah SWT.",
    "footer.mainFeatures": "Main Features",
    "footer.pricePlans": "Pricing Packages",
    "footer.helpCenter": "Help Center",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms & Conditions",

    // About Page
    "about.tag": "About Us",
    "about.heroTitle": "Connecting Hearts with the Holy Land Through Technology",
    "about.heroSubtitle": "Bahrain was born out of a desire to help every pilgrim feel peace of mind and maximum readiness before stepping into the House of Allah.",
    "about.statsDesc": "Pilgrims helped to prepare Hajj & Umrah.",
    "about.missionTitle": "Our Journey Mission",
    "about.missionDesc1": "We understand that Hajj and Umrah journeys are the most sacred once-in-a-lifetime moments. However, lack of familiarity with the field conditions often creates anxiety for prospective pilgrims, especially the elderly.",
    "about.missionDesc2": "Bahrain comes as an immersive bridge. Using 360° VR technology, we present realistic simulations that allow pilgrims to \"be\" at the actual location, memorize routes, and understand the pillars visually before departure.",
    "about.visionTitle": "Our Vision",
    "about.visionDesc": "To become the number one digital manasik education platform in the world that combines sharia and technology.",
    "about.valuesTitle": "Our Values",
    "about.valuesDesc": "Trustworthy in delivering knowledge, Innovative in technology, and Immersive in experience.",
    "about.whyTitle": "Why is Bahrain Different?",
    "about.whySubtitle": "Our innovation is designed to make things easier, not harder.",
    "about.why1Title": "8K Accuracy",
    "about.why1Desc": "All visuals are captured directly at real locations with ultra-high resolution for maximum detail.",
    "about.why2Title": "Integrated Curriculum",
    "about.why2Desc": "Content is structured with experienced mentor ustadzs in accordance with authentic Sharia.",
    "about.why3Title": "High Accessibility",
    "about.why3Desc": "Accessible via smartphones, tablets, computers, to professional VR headsets.",
    "about.ctaTitle": "Join the Digital Manasik Revolution",
    "about.ctaSubtitle": "Improve your worship preparation or your travel group's readiness right now.",
    "about.ctaStart": "Start Now",

    // Pricing Page
    "price.heroTitle": "Invest in Your Worship Preparation",
    "price.heroSubtitle": "Choose the package that best suits your needs for a more mature manasik experience.",
    "price.popular": "Most Popular",
    "price.descBasic": "Suitable for initial manasik introduction.",
    "price.descPremium": "Full experience for individual pilgrims.",
    "price.descTravel": "Efficient solution for travel agencies.",
    "price.descLansia": "Extra guidance for your beloved parents.",
    "price.btnFree": "Start Free",
    "price.btnPremium": "Buy Premium Package",
    "price.btnSales": "Contact Sales",
    "price.btnLansia": "Buy Special Package",
    "price.helpTitle": "Need Help Choosing?",
    "price.helpDesc": "Our team is ready to help you choose the best package or provide a special demo for your Hajj & Umrah travel agency.",
    "price.btnWa": "Contact Us via WhatsApp",
    "price.featBasic1": "1 Main VR Module (Ihram)",
    "price.featBasic2": "Basic Audio Guide",
    "price.featBasic3": "Full Prayer Texts",
    "price.featBasic4": "7 Days Access",
    "price.featPrem1": "All 360° Modules",
    "price.featPrem2": "24/7 Virtual AI Ustadz",
    "price.featPrem3": "Digital Certificate",
    "price.featPrem4": "Lifetime Access",
    "price.featPrem5": "Regular Content Updates",
    "price.featTrav1": "Pilgrim Monitoring Dashboard",
    "price.featTrav2": "Travel Agency Branding",
    "price.featTrav3": "Access for 50+ Pilgrims",
    "price.featTrav4": "API Integration",
    "price.featTrav5": "Priority Support",
    "price.featLan1": "Voice-Command Navigation",
    "price.featLan2": "Very Simple Interface",
    "price.featLan3": "Video Call Guidance (1x)",
    "price.featLan4": "All Premium Features",
    "price.featLan5": "Login Assistance",

    // FAQ Page
    "faq.sub": "Frequently Asked Questions",
    "faq.title": "FREQUENTLY ASKED QUESTIONS",
    "faq.desc": "Everything you need to know about the new manasik learning experience.",
    "faq.cat1": "About Bahrain",
    "faq.q1": "What is Bahrain?",
    "faq.a1": "Bahrain is an education platform for Hajj and Umrah based on 360-degree Virtual Reality (VR) technology that allows pilgrims to experience real simulations in the Holy Land.",
    "faq.q2": "Is this application free?",
    "faq.a2": "We provide a Basic Package for free to try some modules. For full access to all locations and premium features, affordable subscription packages are available.",
    "faq.q3": "What devices are supported?",
    "faq.a3": "Bahrain can be accessed via Smartphones (Android/iOS), Tablets, Laptops, or PCs. For the maximum experience, we recommend using VR glasses.",
    "faq.cat2": "Technology & VR",
    "faq.q4": "Do I have to own VR glasses?",
    "faq.a4": "Not required. You can still enjoy 360-degree content by moving your phone screen or mouse cursor. However, VR glasses will provide a much more realistic immersive experience.",
    "faq.q5": "Are the VR glasses used specific?",
    "faq.a5": "Our platform is compatible with almost all standard VR Boxes as well as high-end VR devices like Oculus/Meta Quest.",
    "faq.cat3": "Account & Payment",
    "faq.q6": "How do I activate the package?",
    "faq.a6": "After making a payment, you will receive an activation code or your package will be automatically active if using instant payment methods (QRIS/Bank Transfer).",
    "faq.q7": "Can it be used for travel groups?",
    "faq.a7": "Absolutely. We have a special Travel Agency package equipped with a monitoring dashboard to view the progress of each pilgrim.",
    "faq.ctaTitle": "Still have other questions?",
    "faq.ctaDesc": "Our support team is ready to answer all your doubts regarding the use of the Bahrain platform.",
    "faq.ctaBtn": "Contact CS Team",

    // Contact Page
    "contact.sub": "Get in Touch",
    "contact.title": "CONTACT US",
    "contact.desc": "We are here to help you prepare for the best spiritual journey of your life.",
    "contact.formTitle": "Send Message",
    "contact.formDesc": "Have a specific question? Fill out the form below and our team will reply within 24 hours.",
    "contact.labelName": "Full Name",
    "contact.phName": "Your Name",
    "contact.labelEmail": "Email",
    "contact.labelSubject": "Subject",
    "contact.optSubject1": "General Question",
    "contact.optSubject2": "Package Activation",
    "contact.optSubject3": "Travel Agency Partnership",
    "contact.optSubject4": "VR Technical Issues",
    "contact.labelMessage": "Message",
    "contact.phMessage": "Write your message here...",
    "contact.btnSubmit": "Send Now",
    "contact.infoOffice": "Headquarters",
    "contact.infoOfficeDesc": "Jl. Jendral Sudirman No. 12, Senayan, Jakarta Selatan, 12190",
    "contact.infoPhone": "Contact Us",
    "contact.infoEmail": "Email Support",

    // Auth Pages
    "auth.welcomeBack": "Welcome Back",
    "auth.loginSubtitle": "Log in to continue your manasik experience",
    "auth.emailLabel": "Email Address",
    "auth.passwordLabel": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.rememberMe": "Remember me",
    "auth.btnLogin": "Log In Now",
    "auth.orWith": "Or log in with",
    "auth.noAccount": "Don't have an account?",
    "auth.registerFree": "Register Free",
    "auth.createAccount": "Create New Account",
    "auth.registerSubtitle": "Start your digital manasik journey today",
    "auth.nameLabel": "Full Name",
    "auth.phName": "Enter your full name",
    "auth.phPassword": "Minimum 8 characters",
    "auth.termsAgree": "I agree to the",
    "auth.termsLink": "Terms & Conditions",
    "auth.and": "and",
    "auth.privacyLink": "Privacy Policy",
    "auth.btnRegister": "Register Now",
    "auth.orRegisterWith": "Or register with",
    "auth.haveAccount": "Already have an account?",
    "auth.loginLink": "Log In Now",

    // Dashboard Home Content
    "dashboard.progTitle": "Module Progress",
    "dashboard.progDesc": "Monitor your Hajj & Umrah preparation progress in real-time.",
    "dashboard.heroTitle": "What is VR Hajj 360°?",
    "dashboard.heroDesc": "VR Hajj delivers interactive simulations to feel the real Hajj pilgrimage experience.",
    "dashboard.watchNow": "Watch Now",

    // Dashboard Packages Content
    "dashpkg.title": "Packages & Activation",
    "dashpkg.subtitle": "Manage your subscription package or activate new modules here.",
    "dashpkg.featuredFeatures": "FEATURED FEATURES:",
    "dashpkg.btnBuy": "Buy Now",
    "dashpkg.currentPkg": "Your Current Package",
    "dashpkg.voucherTitle": "Activate Voucher Code",
    "dashpkg.voucherDesc": "Have an activation code from Hajj Travel or as a gift? Enter the code below to unlock the content instantly.",
    "dashpkg.voucherPlaceholder": "Enter voucher code...",
    "dashpkg.voucherBtn": "Activate Now",
    "dashpkg.active": "Active",
    "dashpkg.popular": "Most Popular",
    "dashpkg.basicName": "Basic Package",
    "dashpkg.basicPeriod": "/ one-time payment",
    "dashpkg.basicFeat1": "Access all video materials",
    "dashpkg.basicFeat2": "Ihram & Tawaf modules (360°)",
    "dashpkg.basicFeat3": "Basic E-Certificate",
    "dashpkg.basicFeat4": "Lifetime access",
    "dashpkg.premName": "Premium VR Package",
    "dashpkg.premPeriod": "/ one-time payment",
    "dashpkg.premFeat1": "All Basic Package features",
    "dashpkg.premFeat2": "Full VR Experience Access (360°)",
    "dashpkg.premFeat3": "24/7 AI Ustadz consultation",
    "dashpkg.premFeat4": "Elderly Manasik Materials",
    "dashpkg.premFeat5": "Priority Module Updates",
    "dashpkg.travName": "Hajj Travel Package",
    "dashpkg.travPeriod": "/ 50 Licenses",
    "dashpkg.travFeat1": "Pilgrim Monitoring Dashboard",
    "dashpkg.travFeat2": "Custom Travel Branding",
    "dashpkg.travFeat3": "Pilgrim Progress Reports",
    "dashpkg.travFeat4": "Travel Schedule Integration",
    "dashpkg.travFeat5": "24/7 Technical Support",
    // Progress Module
    "progress.title": "Module Progress",
    "progress.totalCompletedLabel": "Total Completed",
    "progress.completedStatusText": "You have completed {count} of 6 main modules. Keep it up!",
    "progress.subtitle": "Follow the sequence of manasik guidance below in order according to the rules of Hajj Rukun & Wajib.",
    "progress.tipTitle": "Keep Giving Your Best!",
    "progress.tipDesc": "Complete each step of the hajj rukun discipline to achieve perfection of worship.",
    "progress.certTitle": "Download Progress Certificate",
    "progress.certDesc": "Get a temporary certificate for each module you complete.",
    "progress.lockedToast": "Module Locked!\nPlease complete the previous module up to 100% first to unlock the next manasik journey.",
    "progress.videoWarning": "Warning:\nYou have not finished watching at least 10 seconds. Your video guidance progress will not be saved.",
    "progress.learningPortal": "Manasik Learning Portal",
    "progress.videoStep": "Step 1: Video Tutorial",
    "progress.videoStepDesc": "Watch visual guidance on how to perform (20% progress)",
    "progress.doaStep": "Step 2: Special Prayers & Dzikir",
    "progress.doaStepDesc": "Listen to the mandatory prayers recited (20% progress)",
    "progress.vrStep": "Step 3: Interactive 360° VR Simulation",
    "progress.vrStepDesc": "Complete all interactive field tasks (60% progress)",
    "progress.totalProgress": "Total Module Progress",
    "progress.totalProgressDesc": "Complete the 3 steps above for 100% completion of this module.",
    "progress.btnWatch": "Watch Video",
    "progress.btnOpenDoa": "Open Prayers",
    "progress.btnStartVR": "Start VR",
    "progress.btnComplete": "I Have Memorized & Finished",
    "progress.btnBack": "Back to Steps Portal",
    "progress.btnListen": "Listen",
    "progress.btnPause": "Pause Audio",
    "progress.btnDone": "Done",
    "progress.locked": "Locked",
    "progress.videoCompleted": "Finished Watching Video: {name}",
    "progress.doaCompleted": "Memorized Prayer: {name}",
    "progress.videoHeader": "Module Video Tutorial",
    "progress.videoIntro": "Introduction",
    "progress.videoReq": "Completion Requirement:",
    "progress.videoFinished": "✅ Video Watching Completed",
    "progress.videoWatching": "⏱️ Watching: {watched}s / 10s",
    "progress.doaHeader": "Rukun Prayers & Dzikir",
    "progress.doaIntro": "Special Prayer",
    "progress.recapTitle": "Learning Summary",
    "progress.downloadReport": "Download Report",
    "progress.thMod": "Module",
    "progress.thStatus": "Status",
    "progress.thProgress": "Progress",
    "progress.thTime": "Time",
    "progress.lastAccess": "Last access:",
    "progress.videoCompletedLabel": "Video",
    "progress.doaCompletedLabel": "Prayer",
    "progress.tasksLabel": "Tasks",

    "module.ihram.name": "Module 1: Ihram & Miqat",
    "module.ihram.desc": "Preparation for wearing ihram clothing, ihram prohibitions, and reciting Hajj/Umrah intentions at the Miqat point.",
    "module.tawaf.name": "Module 2: Tawaf at the Kaaba",
    "module.tawaf.desc": "Circling the Kaaba 7 times starting from the Black Stone line accompanied by special prayers.",
    "module.sai.name": "Module 3: Sa\'i Safa-Marwah",
    "module.sai.desc": "Walking and jogging 7 times between Safa Hill and Marwah Hill.",
    "module.wukuf.name": "Module 4: Wukuf in Arafah",
    "module.wukuf.desc": "Standing, reflecting, invoking devoutly, and praying in Arafah Plain on 9 Dzulhijjah.",
    "module.muzdalifah.name": "Module 5: Mabit in Muzdalifah",
    "module.muzdalifah.desc": "Staying overnight in Muzdalifah after sunset from Arafah to pray and collect pebbles.",
    "module.jumrah.name": "Module 6: Throwing Jumrah",
    "module.jumrah.desc": "Throwing Jumrah Ula, Wustha, and Aqabah in Jamarat using pebbles as a symbol of resistance against Satan.",

    // Prayers Page
    "prayers.title": "Prayers & Dzikir",
    "prayers.subtitle": "A collection of answered prayers during your Hajj & Umrah journey.",
    "prayers.searchPlaceholder": "Search for specific prayer...",
    "prayers.noResults": "No prayers found matching your search.",
    "prayers.btnPlay": "Play Audio",
    "prayers.btnPause": "Pause Audio",
    "prayers.tipTitle": "Tips for Memorizing Prayers",
    "prayers.tipDesc": "Use the Play Audio button above to listen to the eloquent recitation of the prayer repeatedly. Memorizing by listening directly is proven to speed up memorization by up to 3x!",
    "prayers.meaning": "Meaning:",
    
    // Categories
    "prayers.cat.all": "All",
    "prayers.cat.ihram": "Ihram Preparation",
    "prayers.cat.tawaf": "Tawaf",
    "prayers.cat.sai": "Sa\'i",
    "prayers.cat.wukuf": "Wukuf",
    "prayers.cat.jumrah": "Throwing Jumrah",

    // Specific Prayers
    "prayer.ihram.title": "Lafal Niat Ihram Hajj & Umrah",
    "prayer.ihram.trans": "I intend to perform Hajj and enter into Ihram for the sake of Allah Ta\'ala.",
    "prayer.talbiyah.title": "Main Talbiyah Sentence",
    "prayer.talbiyah.trans": "I answer Your call, O Allah, I answer Your call. I answer Your call, You have no partner, I answer Your call. Indeed, all praise, grace, and sovereignty belong to You, You have no partner.",
    "prayer.tawaf.title": "Prayer for Starting Tawaf (Black Stone)",
    "prayer.tawaf.trans": "In the name of Allah, and Allah is the Greatest. O Allah, out of faith in You, belief in Your book, and fulfillment of Your covenant.",
    "prayer.sapujagad.title": "Sapu Jagad Prayer (Yamani Corner)",
    "prayer.sapujagad.trans": "Our Lord, give us good in this world and good in the Hereafter, and protect us from the torment of the Fire.",
    "prayer.sai.title": "Prayer for Ascending Safa Hill (Start Sa\'i)",
    "prayer.sai.trans": "Indeed, Safa and Marwah are among the symbols of Allah. I begin with that which Allah began with.",
    "prayer.wukuf.title": "Main Prayer for Standing in Arafah",
    "prayer.wukuf.trans": "There is no deity except Allah alone, without partner. His is the sovereignty, and His is all praise, and He has power over all things.",
    "prayer.jumrah.title": "Prayer When Throwing Jumrah",
    "prayer.jumrah.trans": "In the name of Allah, and Allah is the Greatest. Directing this as expulsion of devils and to please the Most Gracious.",
    "prayer.muzdalifah.title": "Muzdalifah Mabit Zikir",
    "prayer.muzdalifah.trans": "Remember Allah at the holy site (Masy\'aril Haram).",

    // Certificate Page
    "cert.title": "Certificate & Achievements",
    "cert.subtitle": "Tangible proof of your dedication in preparing for the holy journey.",
    "cert.btnDownload": "Download PDF",
    "cert.btnShare": "Share to Social Media",
    "cert.sidebarTitle": "Achievement Badges",
    "cert.whyTitle": "Why is This Certificate Important?",
    "cert.whyDesc": "This certificate shows that you have mastered the rukun, wajib, and procedures of manasik visually and theoretically, increasing your confidence in the field later.",
    "cert.pending": "Pending Completion",
    "cert.inProgress": "In Progress",
    "cert.unlockedDesc": "Completed",
    "cert.achIhram": "Ihram Pioneer",
    "cert.achTawaf": "Tawaf Master",
    "cert.achPilgrim": "Patient Pilgrim",

    // History Page
    "history.title": "Activity History",
    "history.subtitle": "A recording of your preparation journey over time.",
    "history.btnFilter": "Filter Type",
    "history.btnSort": "Sort Newest",
    "history.statSesi": "Total Study Sessions",
    "history.statWaktu": "Simulation Time",
    "history.statDoa": "Memorized Prayers",
    "history.empty": "No activity history yet. Start learning in the module page!",
    "history.btnLoadMore": "Load Previous Activities",
    "history.unitSesi": "Sessions",
    "history.unitJam": "Hours",
    "history.unitMenit": "Minutes",
    "history.unitDoa": "Prayers",
    "history.typeBelajar": "Learning",
    "history.typeSimulasi": "Simulation",
    "history.typeHafalan": "Memorization",

    // Reviews Page
    "reviews.title": "User Reviews",
    "reviews.subtitle": "Hear from other pilgrims or share your own journey stories.",
    "reviews.avgRating": "Average Rating",
    "reviews.basedOn": "Based on {count} reviews",
    "reviews.shareTitle": "Share Your Experience",
    "reviews.shareDesc": "Help other pilgrims by providing a review of your experience using the Bahrain simulation.",
    "reviews.btnWrite": "Write Review Now",
    "reviews.empty": "No reviews have been written yet. Be the first to write a review!",
    "reviews.btnLoadMore": "See More Reviews",
    
    // Review Modal
    "reviews.modalTitle": "Write Your Review",
    "reviews.modalRating": "Your Rating",
    "reviews.modalComment": "Comment / Experience",
    "reviews.modalPlaceholder": "Tell us about your experience using the Bahrain manasik platform...",
    "reviews.modalBtnCancel": "Cancel",
    "reviews.modalBtnSubmit": "Submit Review",
    "reviews.success": "Review submitted successfully!",
    "reviews.error": "Failed to submit review.",

    // Profile Page
    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your personal information and account preferences in real-time.",
    "profile.memberId": "Member ID",
    "profile.securityTip": "Your data is secure and encrypted. We will not share your personal information with anyone.",
    "profile.labelName": "Full Name",
    "profile.labelEmail": "Email",
    "profile.labelPhone": "WhatsApp No.",
    "profile.labelLocation": "Location / City",
    "profile.labelSecurity": "Account Security",
    "profile.labelNewPassword": "New Password",
    "profile.labelConfirmPassword": "Confirm Password",
    "profile.phNewPassword": "Type new password...",
    "profile.phConfirmPassword": "Repeat new password...",
    "profile.btnSave": "Save Changes",
    "profile.success": "Profile updated successfully!",
    "profile.errName": "Name cannot be empty",
    "profile.errEmail": "Email cannot be empty",
    "profile.errConfirm": "Password confirmation does not match",
    "profile.errLength": "New password must be at least 6 characters",
    "profile.errSave": "Failed to update profile.",
    "profile.errConn": "Server connection error occurred.",

    // Help Page
    "help.title": "Help Center",
    "help.subtitle": "Find the fastest answers to your questions and issues.",
    "help.catVR": "VR Tutorial",
    "help.catVRDesc": "How to use VR glasses and navigate the simulation.",
    "help.catAccount": "Account & Billing",
    "help.catAccountDesc": "Login issues, package activation, and payments.",
    "help.catMaterials": "Manasik Curriculum",
    "help.catMaterialsDesc": "Explanation regarding order and educational content.",
    "help.faqTitle": "Frequently Asked Questions (FAQ)",
    
    // Contact Support
    "help.supportTitle": "Need More Help?",
    "help.supportSubTitle": "Contact Our Team",
    "help.supportDesc": "Our support team is ready to help you every day (08:00 - 21:00 WIB).",
    "help.whatsapp": "WhatsApp Support",
    "help.email": "Email Support",
    
    // Feedback
    "help.feedbackTitle": "Have Feedback?",
    "help.feedbackDesc": "We are always open to suggestions to make Bahrain better for all pilgrims.",
    "help.feedbackLink": "Send Feedback",
    
    // Feedback Modal
    "help.modalTitle": "Send Feedback",
    "help.modalDesc": "Your suggestions and criticism are highly valuable for the development of the Bahrain platform.",
    "help.modalTopic": "Feedback Topic",
    "help.modalOpt1": "VR Simulation Issues",
    "help.modalOpt2": "New Feature Suggestions",
    "help.modalOpt3": "Curriculum Feedback",
    "help.modalOpt4": "Others",
    "help.modalMessage": "Message",
    "help.modalPlaceholder": "Write your suggestions or details of issues here...",
    "help.modalBtnCancel": "Cancel",
    "help.modalBtnSubmit": "Send Feedback",
    "help.feedbackSuccess": "Feedback sent successfully! Thank you for your input.",
    "help.feedbackError": "Failed to send feedback.",
    
    // FAQs Detail
    "help.faq.q1": "How do I activate the Premium VR package?",
    "help.faq.a1": "You can enter the voucher code obtained from travel agency in the \'Packages & Activation\' page, or make a direct purchase through our admin WhatsApp.",
    "help.faq.q2": "Can this app be used without VR glasses?",
    "help.faq.a2": "Yes. You can still enjoy the simulation in standard 360-degree mode through your smartphone screen or computer.",
    "help.faq.q3": "My certificate cannot be downloaded, what is the solution?",
    "help.faq.a3": "Make sure all modules in the \'Module Progress\' page are at 100% status. If they are but you still face issues, please contact our IT team.",
    "help.faq.q4": "Will my progress data be saved if I change devices?",
    "help.faq.a4": "Yes, all your progress is saved on the cloud under your account. Simply log back in with the same email on the new device.",
    "cert.locked": "Certificate Locked",
    "cert.lockedDesc": "Complete the entire Bahrain curriculum to download your official certificate.",
    "cert.issuedDateLabel": "Issue Date",
    "cert.idLabel": "Certificate ID",
    "cert.completionDesc": "Has successfully completed the entire digital Hajj manasik simulation program and is declared theoretically ready to perform worship in the Holy Land.",
  },
  ar: {
    // Menu items
    "menu.dashboard": "لوحة التحكم",
    "menu.home": "الرئيسية",
    "menu.packages": "الباقات والتفعيل",
    "menu.progress": "تقدم الوحدات",
    "menu.mainMenu": "القائمة الرئيسية",
    "menu.prayers": "الأدعية والأذكار",
    "menu.certificate": "الشهادات",
    "menu.history": "سجل الأنشطة",
    "menu.reviews": "التقييمات",
    "menu.settings": "الإعدادات",
    "menu.profile": "ملفي الشخصي",
    "menu.help": "المساعدة",
    "menu.logout": "تسجيل الخروج",
    
    // Header
    "header.admin": "المسؤول",
    "header.premium": "عضو ممتاز",
    
    // Dashboard Home
    "dashboard.welcome": "مرحباً،",
    "dashboard.subtitle": "راقب تقدمك في الاستعداد للعبادة والوصول إلى محاكاة المناسك هنا.",
    "dashboard.quickStart": "البدء السريع",
    "dashboard.continueHaji": "متابعة مناسك الحج",
    "dashboard.viewProgress": "عرض التقدم",
    "dashboard.overallProgress": "التقدم العام للرحلة",
    "dashboard.modulesCompleted": "الوحدات المكتملة",
    "dashboard.checklistCompleted": "المهام المكتملة",
    "dashboard.learningGuide": "دليل التعلم",
    
    // Common / Buttons
    "button.close": "إغلاق",
    "button.save": "حفظ",
    "button.submit": "إرسال",

    // Landing Page Navbar
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.features": "الميزات",
    "nav.pricing": "الأسعار",
    "nav.blog": "المدونة",
    "nav.faq": "الأسئلة الشائعة",
    "nav.contact": "اتصل بنا",
    "nav.register": "إنشاء حساب",
    "nav.login": "تسجيل الدخول",

    // Landing Page Hero
    "landing.heroTag": "التعلم الرقمي الغامر",
    "landing.heroTitle": "استعدعبادة الحج بكفاءة وبشكل غامر",
    "landing.heroSubtitle": "تجلب البحرين أجواء الأرض المقدسة إليك مباشرة من خلال تقنية الواقع الافتراضي ثلاثية الأبعاد الواقعية والعميقة.",
    "landing.btnStart": "سجل الآن",
    "landing.btnFeatures": "تعرف على الميزات",
    
    // Landing Page Five Pillars
    "landing.pillarsSub": "الأساسيات",
    "landing.pillarsTitle": "أركان الإسلام الخمسة",
    "landing.pillar1": "الشهادة",
    "landing.pillar2": "الصلاة",
    "landing.pillar3": "الزكاة",
    "landing.pillar4": "الصوم",
    "landing.pillar5": "الحج",
    
    // Landing Page Pricing
    "landing.priceTitle": "ابحث عن الباقة الأنسب لك",
    "landing.priceSubtitle": "اختر باقة التعلم التي تناسب احتياجاتك واشعر بتجربة مناسك أكثر واقعية.",
    "landing.pkgBasic": "الباقة الأساسية",
    "landing.pkgPremium": "الباقة المميزة",
    "landing.pkgTravel": "باقة السفر",
    "landing.pkgLansia": "باقة كبار السن",
    "landing.priceFree": "مجانًا",
    "landing.priceCustom": "مخصص",
    "landing.btnChoose": "اختر الباقة",
    "landing.pkgBasicFeature1": "وحدة واقع افتراضي واحدة",
    "landing.pkgBasicFeature2": "دليل صوتي أساسي",
    "landing.pkgBasicFeature3": "وصول لمدة ٧ أيام",
    "landing.pkgPremiumFeature1": "جميع الوحدات ٣٦٠ درجة",
    "landing.pkgPremiumFeature2": "الأستاذ الافتراضي بالذكاء الاصطناعي",
    "landing.pkgPremiumFeature3": "شهادة رقمية",
    "landing.pkgTravelFeature1": "لوحة مراقبة",
    "landing.pkgTravelFeature2": "تكامل واجهة البرمجة",
    "landing.pkgTravelFeature3": "دعم ذو أولوية",
    "landing.pkgLansiaFeature1": "توجيه صوتي كامل",
    "landing.pkgLansiaFeature2": "تحكم بسيط",
    "landing.pkgLansiaFeature3": "توجيه شخصي",
    
    // Landing Page Why Bahrain
    "landing.whyTitle": "لماذا تختار البحرين؟",
    "landing.why1Title": "دقة بصرية ١٠٠٪",
    "landing.why1Desc": "يتم تصوير جميع المواقع مباشرة في الأرض المقدسة باستخدام كاميرات بدقة 8K.",
    "landing.why2Title": "المساعدة بالذكاء الاصطناعي",
    "landing.why2Desc": "اسأل عن أحكام المناسك في أي وقت مع مساعد الذكاء الاصطناعي المدرب.",
    "landing.why3Title": "الشهادات الرسمية",
    "landing.why3Desc": "احصل على شهادة رقمية بعد إكمال سلسلة المحاكاة بأكملها.",
    
    // Landing Page Testimonials
    "landing.testiSub": "ماذا يقولون؟",
    "landing.testiTitle": "أحدث تقييمات حجاجنا",
    "landing.testiDesc": "استمع إلى قصص حقيقية من الحجاج الذين أكملوا استعداداتهم للحج مع البحرين.",
    "landing.noTestimonials": "لم يتم إرسال أي تقييمات حديثة بعد.",

    // Landing Page Blog
    "landing.blogSub": "أحدث المقالات والأخبار",
    "landing.blogTitle": "أفضل دليل وفقه للمناسك",
    "landing.blogDesc": "أثري معرفتك بالمناسك من خلال مجموعة من المقالات الإرشادية والفقه العملي ونصائح السفر المنسقة من قبل علماء خبراء.",
    "landing.noBlogs": "لم يتم نشر أي مقالات إرشادية بعد.",
    "landing.blogReadMore": "اقرأ المزيد",

    // Footer
    "footer.desc": "مساعدة الحجاج على الاستعداد لأفضل رحلة روحية لهم من خلال تقنية غامرة واقعية وموثوقة.",
    "footer.nav": "التنقل",
    "footer.support": "الدعم",
    "footer.contact": "اتصل بنا",
    "footer.contactDesc": "هل لديك أسئلة؟ نحن مستعدون للمساعدة في استعداداتك.",
    "footer.copyright": "© ٢٠٢٦ البحرين. جميع الحقوق محفوظة لله سبحانه وتعالى.",
    "footer.mainFeatures": "الميزات الرئيسية",
    "footer.pricePlans": "باقات الأسعار",
    "footer.helpCenter": "مركز المساعدة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "الشروط والأحكام",

    // About Page
    "about.tag": "من نحن",
    "about.heroTitle": "ربط القلوب بالأرض المقدسة من خلال التكنولوجيا",
    "about.heroSubtitle": "ولدت البحرين من الرغبة في مساعدة كل حاج على الشعور بسلام داخلي والاستعداد التام قبل خطوته إلى بيت الله الحرام.",
    "about.statsDesc": "مساعدة الحجاج في الاستعداد للحج والعمرة.",
    "about.missionTitle": "مهمة رحلتنا",
    "about.missionDesc1": "نحن نتفهم أن رحلات الحج والعمرة هي أقدس اللحظات التي تحدث مرة واحدة في العمر. ومع ذلك، فإن عدم الإلمام بظروف الميدان غالبًا ما يسبب القلق للحجاج المحتملين، وخاصة كبار السن.",
    "about.missionDesc2": "تأتي البحرين كجسر غامر. باستخدام تقنية الواقع الافتراضي ٣٦٠ درجة، نقدم محاكاة واقعية تتيح للحجاج \"التواجد\" في الموقع الفعلي وحفظ المسارات وفهم الأركان بصريًا قبل المغادرة.",
    "about.visionTitle": "رؤيتنا",
    "about.visionDesc": "أن نصبح المنصة الرقمية الأولى لتعليم المناسك في العالم التي تجمع بين الشريعة والتكنولوجيا.",
    "about.valuesTitle": "قيمنا",
    "about.valuesDesc": "الأمانة في إيصال العلم، والابتكار في التكنولوجيا، والانغماس في التجربة.",
    "about.whyTitle": "لماذا تختلف البحرين؟",
    "about.whySubtitle": "تم تصميم ابتكارنا لتسهيل الأمور، وليس تعقيدها.",
    "about.why1Title": "دقة 8K",
    "about.why1Desc": "يتم التقاط جميع المرئيات مباشرة في مواقع حقيقية بدقة فائقة للحصول على أقصى قدر من التفاصيل.",
    "about.why2Title": "منهج متكامل",
    "about.why2Desc": "تم تنظيم المحتوى مع أساتذة مرشدين ذوي خبرة وفقًا للشريعة الصحيحة.",
    "about.why3Title": "سهولة وصول عالية",
    "about.why3Desc": "يمكن الوصول إليه عبر الهواتف الذكية والأجهزة اللوحية وأجهزة الكمبيوتر وسماعات الواقع الافتراضي الاحترافية.",
    "about.ctaTitle": "انضم إلى ثورة المناسك الرقمية",
    "about.ctaSubtitle": "حسن استعدادك للعبادة أو استعداد مجموعة سفرك الآن.",
    "about.ctaStart": "ابدأ الآن",

    // Pricing Page
    "price.heroTitle": "استثمر في استعدادك للعبادة",
    "price.heroSubtitle": "اختر الباقة الأنسب لاحتياجاتك لتجربة مناسك أكثر نضجًا.",
    "price.popular": "الأكثر شيوعًا",
    "price.descBasic": "مناسب للمقدمة الأولية للمناسك.",
    "price.descPremium": "تجربة كاملة للحجاج الأفراد.",
    "price.descTravel": "حل فعال لوكالات السفر.",
    "price.descLansia": "إرشاد إضافي لوالديك الحبيبين.",
    "price.btnFree": "ابدأ مجانًا",
    "price.btnPremium": "شراء الباقة المميزة",
    "price.btnSales": "اتصل بالمبيعات",
    "price.btnLansia": "شراء باقة خاصة",
    "price.helpTitle": "هل تحتاج إلى مساعدة في الاختيار؟",
    "price.helpDesc": "فريقنا مستعد لمساعدتك في اختيار الباقة الأفضل أو تقديم عرض توضيحي خاص لوكالة سفر الحج والعمرة الخاصة بك.",
    "price.btnWa": "اتصل بنا عبر الواتساب",
    "price.featBasic1": "وحدة واقع افتراضي رئيسية واحدة (الإحرام)",
    "price.featBasic2": "دليل صوتي أساسي",
    "price.featBasic3": "نصوص الأدعية الكاملة",
    "price.featBasic4": "وصول لمدة ٧ أيام",
    "price.featPrem1": "جميع الوحدات ٣٦٠ درجة",
    "price.featPrem2": "الأستاذ الافتراضي بالذكاء الاصطناعي على مدار الساعة",
    "price.featPrem3": "شهادة رقمية",
    "price.featPrem4": "وصول مدى الحياة",
    "price.featPrem5": "تحديثات المحتوى الدورية",
    "price.featTrav1": "لوحة مراقبة الحجاج",
    "price.featTrav2": "العلامة التجارية لوكالة السفر",
    "price.featTrav3": "وصول لأكثر من ٥٠ حاجًا",
    "price.featTrav4": "تكامل واجهة برمجة التطبيقات",
    "price.featTrav5": "دعم ذو أولوية",
    "price.featLan1": "التنقل بالأوامر الصوتية",
    "price.featLan2": "واجهة بسيطة للغاية",
    "price.featLan3": "إرشاد عبر مكالمة فيديو (مرة واحدة)",
    "price.featLan4": "جميع الميزات المميزة",
    "price.featLan5": "مساعدة في تسجيل الدخول",

    // FAQ Page
    "faq.sub": "Frequently Asked Questions",
    "faq.title": "الأسئلة الشائعة",
    "faq.desc": "كل ما تحتاج إلى معرفته عن تجربة تعلم المناسك الجديدة.",
    "faq.cat1": "حول البحرين",
    "faq.q1": "ما هي البحرين؟",
    "faq.a1": "البحرين هي منصة تعليمية لمناسك الحج والعمرة تعتمد على تقنية الواقع الافتراضي ٣٦٠ درجة التي تتيح للحجاج تجربة محاكاة واقعية في الأرض المقدسة.",
    "faq.q2": "هل هذا التطبيق مجاني؟",
    "faq.a2": "نحن نقدم الباقة الأساسية مجانًا لتجربة بعض الوحدات. وللوصول الكامل إلى جميع المواقع والميزات المميزة، تتوفر باقات اشتراك بأسعار معقولة.",
    "faq.q3": "ما هي الأجهزة المدعومة؟",
    "faq.a3": "يمكن الوصول إلى البحرين عبر الهواتف الذكية والأجهزة اللوحية وأجهزة الكمبيوتر المحمولة أو أجهزة الكمبيوتر المكتبية. للحصول على أقصى قدر من التجربة، نوصي باستخدام نظارات الواقع الافتراضي.",
    "faq.cat2": "التكنولوجيا والواقع الافتراضي",
    "faq.q4": "هل يجب أن أمتلك نظارات واقع افتراضي؟",
    "faq.a4": "ليس إلزاميًا. لا يزال بإمكانك الاستمتاع بمحتوى ٣٦٠ درجة عن طريق تحريك شاشة هاتفك أو مؤصل الماوس. ومع ذلك، ستوفر نظارات الواقع الافتراضي تجربة غامرة أكثر واقعية بكثير.",
    "faq.q5": "هل نظارات الواقع الافتراضي المستخدمة خاصة؟",
    "faq.a5": "منصتنا متوافقة مع جميع صناديق الواقع الافتراضي القياسية تقريبًا بالإضافة إلى أجهزة الواقع الافتراضي المتطورة مثل Oculus/Meta Quest.",
    "faq.cat3": "الحساب والدفع",
    "faq.q6": "كيف يمكنني تفعيل الباقة؟",
    "faq.a6": "بعد إجراء الدفع، ستتلقى رمز تفعيل أو سيتم تفعيل باقتك تلقائيًا في حال استخدام طرق الدفع الفورية (QRIS/التحويل البنكي).",
    "faq.q7": "هل يمكن استخدامها للمجموعات السياحية؟",
    "faq.a7": "بكل تأكيد. لدينا باقة خاصة لوكالات السفر مجهزة بلوحة مراقبة لمشاهدة تقدم كل حاج.",
    "faq.ctaTitle": "هل لا يزال لديك أسئلة أخرى؟",
    "faq.ctaDesc": "فريق الدعم لدينا مستعد للإجابة على جميع شكوكك المتعلقة باستخدام منصة البحرين.",
    "faq.ctaBtn": "اتصل بفريق خدمة العملاء",

    // Contact Page
    "contact.sub": "Get in Touch",
    "contact.title": "اتصل بنا",
    "contact.desc": "نحن هنا لمساعدتك في الاستعداد لأفضل رحلة روحية في حياتك.",
    "contact.formTitle": "إرسال رسالة",
    "contact.formDesc": "هل لديك سؤال محدد؟ املأ النموذج أدناه وسيقوم فريقنا بالرد خلال ٢٤ ساعة.",
    "contact.labelName": "الاسم الكامل",
    "contact.phName": "اسمك",
    "contact.labelEmail": "البريد الإلكتروني",
    "contact.labelSubject": "الموضوع",
    "contact.optSubject1": "سؤال عام",
    "contact.optSubject2": "تفعيل الباقة",
    "contact.optSubject3": "شراكة وكالة السفر",
    "contact.optSubject4": "مشاكل تقنية في الواقع الافتراضي",
    "contact.labelMessage": "الرسالة",
    "contact.phMessage": "اكتب رسالتك هنا...",
    "contact.btnSubmit": "إرسال الآن",
    "contact.infoOffice": "المكتب الرئيسي",
    "contact.infoOfficeDesc": "Jl. Jendral Sudirman No. 12, Senayan, Jakarta Selatan, 12190",
    "contact.infoPhone": "اتصل بنا",
    "contact.infoEmail": "دعم البريد الإلكتروني",

    // Auth Pages
    "auth.welcomeBack": "مرحبًا بعودتك",
    "auth.loginSubtitle": "سجل الدخول لمواصلة تجربة المناسك الخاصة بك",
    "auth.emailLabel": "البريد الإلكتروني",
    "auth.passwordLabel": "كلمة المرور",
    "auth.forgotPassword": "هل نسيت كلمة المرور؟",
    "auth.rememberMe": "تذكرني",
    "auth.btnLogin": "سجل الدخول الآن",
    "auth.orWith": "أو سجل الدخول بواسطة",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.registerFree": "سجل مجانًا",
    "auth.createAccount": "إنشاء حساب جديد",
    "auth.registerSubtitle": "ابدأ رحلة المناسك الرقمية اليوم",
    "auth.nameLabel": "الاسم الكامل",
    "auth.phName": "أدخل اسمك الكامل",
    "auth.phPassword": "على الأقل ٨ أحرف",
    "auth.termsAgree": "أنا أوافق على",
    "auth.termsLink": "الشروط والأحكام",
    "auth.and": "و",
    "auth.privacyLink": "سياسة الخصوصية",
    "auth.btnRegister": "سجل الآن",
    "auth.orRegisterWith": "أو سجل بواسطة",
    "auth.haveAccount": "لديك حساب بالفعل؟",
    "auth.loginLink": "سجل الدخول الآن",

    // Dashboard Home Content
    "dashboard.progTitle": "تقدم الوحدات",
    "dashboard.progDesc": "راقب تقدمك في الاستعداد للحج والعمرة في الوقت الفعلي.",
    "dashboard.heroTitle": "ما هو الواقع الافتراضي للحج ٣٦٠ درجة؟",
    "dashboard.heroDesc": "يوفر الواقع الافتراضي للحج محاكاة تفاعلية للشعور بتجربة الحج الحقيقية.",
    "dashboard.watchNow": "شاهد الآن",

    // Dashboard Packages Content
    "dashpkg.title": "الباقات والتفعيل",
    "dashpkg.subtitle": "إدارة باقة الاشتراك الخاصة بك أو تفعيل وحدات جديدة هنا.",
    "dashpkg.featuredFeatures": "الميزات المميزة:",
    "dashpkg.btnBuy": "شراء الآن",
    "dashpkg.currentPkg": "باقتك الحالية",
    "dashpkg.voucherTitle": "تفعيل رمز القسيمة",
    "dashpkg.voucherDesc": "هل لديك رمز تفعيل من وكالة السفر للحج أو كهدية؟ أدخل الرمز أدناه لفتح المحتوى فورًا.",
    "dashpkg.voucherPlaceholder": "أدخل رمز القسيمة...",
    "dashpkg.voucherBtn": "تفعيل الآن",
    "dashpkg.active": "نشط",
    "dashpkg.popular": "الأكثر شيوعًا",
    "dashpkg.basicName": "الباقة الأساسية",
    "dashpkg.basicPeriod": "/ دفع لمرة واحدة",
    "dashpkg.basicFeat1": "الوصول إلى جميع مواد الفيديو",
    "dashpkg.basicFeat2": "وحدات الإحرام والطواف (٣٦٠ درجة)",
    "dashpkg.basicFeat3": "شهادة إلكترونية أساسية",
    "dashpkg.basicFeat4": "وصول مدى الحياة",
    "dashpkg.premName": "الباقة المميزة للواقع الافتراضي",
    "dashpkg.premPeriod": "/ دفع لمرة واحدة",
    "dashpkg.premFeat1": "جميع ميزات الباقة الأساسية",
    "dashpkg.premFeat2": "وصول كامل لتجربة الواقع الافتراضي (٣٦٠ درجة)",
    "dashpkg.premFeat3": "استشارة الأستاذ الافتراضي بالذكاء الاصطناعي على مدار الساعة",
    "dashpkg.premFeat4": "مواد المناسك لكبار السن",
    "dashpkg.premFeat5": "أولوية تحديث الوحدات",
    "dashpkg.travName": "باقة سفر الحج",
    "dashpkg.travPeriod": "/ ٥٠ ترخيصًا",
    "dashpkg.travFeat1": "لوحة مراقبة الحجاج",
    "dashpkg.travFeat2": "علامة تجارية مخصصة للسفر",
    "dashpkg.travFeat3": "تقارير تقدم الحجاج",
    "dashpkg.travFeat4": "دمج جدول السفر",
    "dashpkg.travFeat5": "دعم فني على مدار الساعة",
    // Progress Module
    "progress.title": "تقدم الوحدات",
    "progress.totalCompletedLabel": "إجمالي المكتمل",
    "progress.completedStatusText": "لقد أكملت {count} من أصل ٦ وحدات رئيسية. استمر في ذلك!",
    "progress.subtitle": "اتبع تسلسل إرشادات المناسك أدناه بالترتيب وفقًا لأحكام أركان وواجبات الحج.",
    "progress.tipTitle": "استمر في تقديم أفضل ما لديك!",
    "progress.tipDesc": "أكمل كل خطوة من خطوات انضباط أركان الحج لتحقيق كمال العبادة.",
    "progress.certTitle": "تحميل شهادة التقدم",
    "progress.certDesc": "احصل على شهادة مؤقتة لكل وحدة تكملها.",
    "progress.lockedToast": "الوحدة مغلقة!\nيرجى إكمال الوحدة السابقة بنسبة 100% أولاً لفتح رحلة المناسك التالية.",
    "progress.videoWarning": "تحذير:\nلم تنتهِ من المشاهدة لمدة 10 ثوانٍ على الأقل. لن يتم حفظ تقدم الإرشادات المرئية الخاص بك.",
    "progress.learningPortal": "بوابة تعلم المناسك",
    "progress.videoStep": "الخطوة ١: فيديو توضيحي",
    "progress.videoStepDesc": "شاهد إرشادات مرئية حول كيفية الأداء (20% تقدم)",
    "progress.doaStep": "الخطوة ٢: أدعية وأذكار خاصة",
    "progress.doaStepDesc": "استمع إلى الأدعية المفروضة التي يتم تلاوتها (20% تقدم)",
    "progress.vrStep": "الخطوة ٣: محاكاة واقع افتراضي تفاعلية ٣٦٠ درجة",
    "progress.vrStepDesc": "أكمل جميع المهام التفاعلية الميدانية (60% تقدم)",
    "progress.totalProgress": "إجمالي تقدم الوحدة",
    "progress.totalProgressDesc": "أكمل الخطوات الثلاث المذكورة أعلاه لإكمال هذه الوحدة بنسبة 100%.",
    "progress.btnWatch": "شاهد الفيديو",
    "progress.btnOpenDoa": "افتح الأدعية",
    "progress.btnStartVR": "ابدأ الواقع الافتراضي",
    "progress.btnComplete": "لقد حفظت وأنهيت",
    "progress.btnBack": "العودة إلى بوابة الخطوات",
    "progress.btnListen": "استمع",
    "progress.btnPause": "إيقاف مؤقت للصوت",
    "progress.btnDone": "تم",
    "progress.locked": "مغلق",
    "progress.videoCompleted": "تم الانتهاء من مشاهدة الفيديو: {name}",
    "progress.doaCompleted": "تم حفظ الدعاء: {name}",
    "progress.videoHeader": "فيديو توضيحي للوحدة",
    "progress.videoIntro": "مقدمة",
    "progress.videoReq": "متطلبات الإكمال:",
    "progress.videoFinished": "✅ اكتملت مشاهدة الفيديو",
    "progress.videoWatching": "⏱️ مشاهدة: {watched} ث / ١٠ ث",
    "progress.doaHeader": "أدعية وأذكار الركن",
    "progress.doaIntro": "دعاء خاص",
    "progress.recapTitle": "ملخص التعلم",
    "progress.downloadReport": "تحميل التقرير",
    "progress.thMod": "الوحدة",
    "progress.thStatus": "الحالة",
    "progress.thProgress": "التقدم",
    "progress.thTime": "الوقت",
    "progress.lastAccess": "آخر وصول:",
    "progress.videoCompletedLabel": "فيديو",
    "progress.doaCompletedLabel": "دعاء",
    "progress.tasksLabel": "مهام",

    "module.ihram.name": "الوحدة ١: الإحرام والميقات",
    "module.ihram.desc": "الاستعداد لارتداء ملابس الإحرام، ومحظورات الإحرام، وتلاوة نية الحج/العمرة عند نقطة الميقات.",
    "module.tawaf.name": "الوحدة ٢: الطواف حول الكعبة",
    "module.tawaf.desc": "الطواف حول الكعبة 7 مرات بدءًا من خط الحجر الأسود مصحوبًا بأدعية خاصة.",
    "module.sai.name": "الوحدة ٣: السعي بين الصفا والمروة",
    "module.sai.desc": "المشي والهرولة 7 مرات بين جبل الصفا وجبل المروة.",
    "module.wukuf.name": "الوحدة ٤: الوقوف بعرفة",
    "module.wukuf.desc": "الوقوف والتأمل والدعاء بخشوع والصلاة في صعيد عرفة في اليوم التاسع من ذي الحجة.",
    "module.muzdalifah.name": "الوحدة ٥: المبيت بمزدلفة",
    "module.muzdalifah.desc": "المبيت في مزدلفة بعد غروب الشمس من عرفة للدعاء وجمع الحصى.",
    "module.jumrah.name": "الوحدة ٦: رمي الجمرات",
    "module.jumrah.desc": "رمي جمرة العقبة والصغرى والوسطى في الجمرات باستخدام الحصى كرمز لمقاومة الشيطان.",

    // Prayers Page
    "prayers.title": "الأدعية والأذكار",
    "prayers.subtitle": "مجموعة من الأدعية المستجابة خلال رحلة الحج والعمرة.",
    "prayers.searchPlaceholder": "البحث عن دعاء محدد...",
    "prayers.noResults": "لم يتم العثور على أدعية تطابق بحثك.",
    "prayers.btnPlay": "تشغيل الصوت",
    "prayers.btnPause": "إيقاف مؤقت",
    "prayers.tipTitle": "نصائح لحفظ الأدعية",
    "prayers.tipDesc": "استخدم زر تشغيل الصوت أعلاه للاستماع إلى التلاوة البليغة للدعاء بشكل متكرر. ثبت أن الحفظ من خلال الاستماع المباشر يسرع الحفظ بمعدل يصل إلى 3 مرات!",
    "prayers.meaning": "المعنى:",
    
    // Categories
    "prayers.cat.all": "الكل",
    "prayers.cat.ihram": "الاستعداد للإحرام",
    "prayers.cat.tawaf": "الطواف",
    "prayers.cat.sai": "السعي",
    "prayers.cat.wukuf": "الوقوف",
    "prayers.cat.jumrah": "رمي الجمرات",

    // Specific Prayers
    "prayer.ihram.title": "لفظ نية إحرام الحج والعمرة",
    "prayer.ihram.trans": "نويت الحج وأحرمت به لله تعالى.",
    "prayer.talbiyah.title": "صيغة التلبية الرئيسية",
    "prayer.talbiyah.trans": "لبيك اللهم لبيك، لبيك لا شريك لك لبيك. إن الحمد والنعمة لك والملك، لا شريك لك.",
    "prayer.tawaf.title": "الدعاء عند بدء الطواف (الحجر الأسود)",
    "prayer.tawaf.trans": "بسم الله والله أكبر، اللهم إيمانًا بك وتصديقًا بكتابك ووفاء بعهدك.",
    "prayer.sapujagad.title": "دعاء ربنا آتنا في الدنيا حسنة",
    "prayer.sapujagad.trans": "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار.",
    "prayer.sai.title": "الدعاء عند صعود الصفا (بدء السعي)",
    "prayer.sai.trans": "إن الصفا والمروة من شعائر الله. أبدأ بما بدأ الله به.",
    "prayer.wukuf.title": "الدعاء الرئيسي للوقوف بعرفة",
    "prayer.wukuf.trans": "لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.",
    "prayer.jumrah.title": "الدعاء عند رمي الجمرات",
    "prayer.jumrah.trans": "بسم الله والله أكبر، رغماً للشياطين ورضى للرحمن.",
    "prayer.muzdalifah.title": "ذكر المبيت بمزدلفة",
    "prayer.muzdalifah.trans": "فاذكروا الله عند المشعر الحرام.",

    // Certificate Page
    "cert.title": "الشهادات والإنجازات",
    "cert.subtitle": "دليل ملموس على تفانيك في الاستعداد للرحلة المقدسة.",
    "cert.btnDownload": "تحميل PDF",
    "cert.btnShare": "مشاركة على وسائل التواصل الاجتماعي",
    "cert.sidebarTitle": "شارات الإنجاز",
    "cert.whyTitle": "لماذا هذه الشهادة مهمة؟",
    "cert.whyDesc": "تظهر هذه الشهادة أنك أتقنت أركان وواجبات وإجراءات المناسك بصريًا ونظريًا، مما يزيد من ثقتك في الميدان لاحقًا.",
    "cert.pending": "في انتظار الإكمال",
    "cert.inProgress": "قيد التنفيذ",
    "cert.unlockedDesc": "مكتمل",
    "cert.achIhram": "رائد الإحرام",
    "cert.achTawaf": "خبير الطواف",
    "cert.achPilgrim": "الحاج الصبور",

    // History Page
    "history.title": "سجل الأنشطة",
    "history.subtitle": "تسجيل لرحلتك التحضيرية بمرور الوقت.",
    "history.btnFilter": "تصفية النوع",
    "history.btnSort": "ترتيب الأحدث",
    "history.statSesi": "إجمالي جلسات الدراسة",
    "history.statWaktu": "وقت المحاكاة",
    "history.statDoa": "الأدعية المحفوظة",
    "history.empty": "لا يوجد سجل أنشطة بعد. ابدأ التعلم في صفحة الوحدات!",
    "history.btnLoadMore": "تحميل الأنشطة السابقة",
    "history.unitSesi": "جلسات",
    "history.unitJam": "ساعات",
    "history.unitMenit": "دقائق",
    "history.unitDoa": "أدعية",
    "history.typeBelajar": "دراسة",
    "history.typeSimulasi": "محاكاة",
    "history.typeHafalan": "حفظ",

    // Reviews Page
    "reviews.title": "تقييمات المستخدمين",
    "reviews.subtitle": "استمع إلى حجاج آخرين أو شارك قصص رحلتك الخاصة.",
    "reviews.avgRating": "متوسط التقييم",
    "reviews.basedOn": "بناءً على {count} تقييمات",
    "reviews.shareTitle": "شارك تجربتك",
    "reviews.shareDesc": "ساعد الحجاج الآخرين من خلال تقديم تقييم لتجربتك في استخدام محاكاة البحرين.",
    "reviews.btnWrite": "اكتب تقييمًا الآن",
    "reviews.empty": "لم يتم كتابة أي تقييمات بعد. كن أول من يكتب تقييمًا!",
    "reviews.btnLoadMore": "شاهد المزيد من التقييمات",
    
    // Review Modal
    "reviews.modalTitle": "اكتب تقييمك",
    "reviews.modalRating": "تقييمك",
    "reviews.modalComment": "التعليق / التجربة",
    "reviews.modalPlaceholder": "أخبرنا عن تجربتك في استخدام منصة مناسك البحرين...",
    "reviews.modalBtnCancel": "إلغاء",
    "reviews.modalBtnSubmit": "إرسال التقييم",
    "reviews.success": "تم إرسال التقييم بنجاح!",
    "reviews.error": "فشل في إرسال التقييم.",

    // Profile Page
    "profile.title": "إعدادات الملف الشخصي",
    "profile.subtitle": "إدارة معلوماتك الشخصية وتفضيلات حسابك في الوقت الفعلي.",
    "profile.memberId": "رقم العضوية",
    "profile.securityTip": "بياناتك آمنة ومشفرة. لن نشارك معلوماتك الشخصية مع أي شخص.",
    "profile.labelName": "الاسم الكامل",
    "profile.labelEmail": "البريد الإلكتروني",
    "profile.labelPhone": "رقم الواتساب",
    "profile.labelLocation": "الموقع / المدينة",
    "profile.labelSecurity": "أمان الحساب",
    "profile.labelNewPassword": "كلمة مرور جديدة",
    "profile.labelConfirmPassword": "تأكيد كلمة المرور",
    "profile.phNewPassword": "اكتب كلمة مرور جديدة...",
    "profile.phConfirmPassword": "كرر كلمة المرور الجديدة...",
    "profile.btnSave": "حفظ التغييرات",
    "profile.success": "تم تحديث الملف الشخصي بنجاح!",
    "profile.errName": "الاسم لا يمكن أن يكون فارغاً",
    "profile.errEmail": "البريد الإلكتروني لا يمكن أن يكون فارغاً",
    "profile.errConfirm": "تأكيد كلمة المرور غير متطابق",
    "profile.errLength": "يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل",
    "profile.errSave": "فشل في تحديث الملف الشخصي.",
    "profile.errConn": "حدث خطأ في الاتصال بالخادم.",

    // Help Page
    "help.title": "مركز المساعدة",
    "help.subtitle": "ابحث عن أسرع الإجابات لأسئلتك ومشاكلك.",
    "help.catVR": "شرح الواقع الافتراضي",
    "help.catVRDesc": "كيفية استخدام نظارات الواقع الافتراضي والتنقل في المحاكاة.",
    "help.catAccount": "الحساب والفواتير",
    "help.catAccountDesc": "مشاكل تسجيل الدخول وتفعيل الباقة والمدفوعات.",
    "help.catMaterials": "منهج المناسك",
    "help.catMaterialsDesc": "شرح يتعلق بالترتيب والمحتوى التعليمي.",
    "help.faqTitle": "الأسئلة الشائعة (FAQ)",
    
    // Contact Support
    "help.supportTitle": "هل تحتاج إلى مزيد من المساعدة؟",
    "help.supportSubTitle": "اتصل بفريقنا",
    "help.supportDesc": "فريق الدعم لدينا مستعد لمساعدتك كل يوم (08:00 - 21:00 بتوقيت غرب إندونيسيا).",
    "help.whatsapp": "دعم الواتساب",
    "help.email": "دعم البريد الإلكتروني",
    
    // Feedback
    "help.feedbackTitle": "هل لديك ملاحظات؟",
    "help.feedbackDesc": "نحن منفتحون دائماً على الاقتراحات لجعل البحرين أفضل لجميع الحجاج.",
    "help.feedbackLink": "إرسال ملاحظات",
    
    // Feedback Modal
    "help.modalTitle": "إرسال ملاحظات",
    "help.modalDesc": "اقتراحاتك وانتقاداتك قيمة للغاية لتطوير منصة البحرين.",
    "help.modalTopic": "موضوع الملاحظات",
    "help.modalOpt1": "مشاكل محاكاة الواقع الافتراضي",
    "help.modalOpt2": "اقتراحات ميزات جديدة",
    "help.modalOpt3": "ملاحظات المنهج الدراسي",
    "help.modalOpt4": "أخرى",
    "help.modalMessage": "الرسالة",
    "help.modalPlaceholder": "اكتب اقتراحاتك أو تفاصيل المشاكل هنا...",
    "help.modalBtnCancel": "إلغاء",
    "help.modalBtnSubmit": "إرسال الملاحظات",
    "help.feedbackSuccess": "تم إرسال الملاحظات بنجاح! شكراً لك.",
    "help.feedbackError": "فشل في إرسال الملاحظات.",
    
    // FAQs Detail
    "help.faq.q1": "كيف يمكنني تفعيل باقة Premium VR؟",
    "help.faq.a1": "يمكنك إدخال رمز القسيمة المستلم من وكالة السفر في صفحة \'الباقات والتفعيل\'، أو الشراء المباشر عبر واتساب الإدارة الخاص بنا.",
    "help.faq.q2": "هل يمكن استخدام هذا التطبيق بدون نظارات الواقع الافتراضي؟",
    "help.faq.a2": "نعم. لا يزال بإمكانك الاستمتاع بالمحاكاة في وضع ٣٦٠ درجة القياسي من خلال شاشة هاتفك الذكي أو الكمبيوتر.",
    "help.faq.q3": "لا يمكنني تحميل شهادتي، ما الحل؟",
    "help.faq.a3": "تأكد من أن جميع الوحدات في صفحة \'تقدم الوحدات\' في حالة مكتملة بنسبة 100%. إذا كانت كذلك ولا تزال تواجه مشكلة، يرجى الاتصال بفريق تكنولوجيا المعلومات لدينا.",
    "help.faq.q4": "هل سيتم حفظ بيانات التقدم الخاصة بي إذا قمت بتغيير الأجهزة؟",
    "help.faq.a4": "نعم، يتم حفظ كل تقدمك على السحابة تحت حسابك. ما عليك سوى تسجيل الدخول مرة أخرى باستخدام نفس البريد الإلكتروني على الجهاز الجديد.",
    "cert.locked": "الشهادة مغلقة",
    "cert.lockedDesc": "أكمل منهج البحرين بالكامل لتنزيل شهادتك الرسمية.",
    "cert.issuedDateLabel": "تاريخ الإصدار",
    "cert.idLabel": "معرف الشهادة",
    "cert.completionDesc": "قد أكمل بنجاح برنامج محاكاة مناسك الحج الرقمي بالكامل وتم إعلانه مستعداً نظرياً لأداء العبادة في الأرض المقدسة.",
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("id");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const storedLang = localStorage.getItem("bahrain_language") as Language;
    if (storedLang === "id" || storedLang === "en" || storedLang === "ar") {
      setLanguageState(storedLang);
    } else {
      const browserLang = navigator.language || (navigator as any).userLanguage || "";
      let defaultLang: Language = "id";
      if (browserLang.toLowerCase().startsWith("ar")) {
        defaultLang = "ar";
      } else if (browserLang.toLowerCase().startsWith("en")) {
        defaultLang = "en";
      }
      setLanguageState(defaultLang);
      localStorage.setItem("bahrain_language", defaultLang);
    }
    setIsInitialized(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("bahrain_language", lang);
  };

  const t = (key: string): string => {
    const langDict = translations[language] || translations.id;
    return (langDict as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {isInitialized ? children : <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="w-10 h-10 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin"></div>
      </div>}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
